### ISSUE TITLE
Performance issue with combined zarr sources

### ISSUE THREAD

**Issue by dmedv** [fsspec/kerchunk#118]
I am trying to use kerchunk to access a distributed collection of zarr arrays, parts of a large dataset split by the 'time' dimension.
Each zarr array is accessible through its own NFS-mounted directory on the machine where the code is running.
Here is the entire test code with some output in the comments:
```python
from kerchunk.zarr import single_zarr
from kerchunk.combine import MultiZarrToZarr
import fsspec
import zarr
import xarray

prefix = '/home/idies/workspace/poseidon/'
suffix = '/llc4320_tests/10dayhourly/velocities'
combined_json = 'file:///home/idies/workspace/combined.json'

refs = []
for node in range(1, 11):
    for dir in range(1, 4):
        path = prefix + f'data{node:02}_{dir:02}' + suffix
        refs.append(single_zarr(path))
        print(path)

# /home/idies/workspace/poseidon/data01_01/llc4320_tests/10dayhourly/velocities
# /home/idies/workspace/poseidon/data01_02/llc4320_tests/10dayhourly/velocities
# /home/idies/workspace/poseidon/data01_03/llc4320_tests/10dayhourly/velocities
# /home/idies/workspace/poseidon/data02_01/llc4320_tests/10dayhourly/velocities
# ...

mz2z = MultiZarrToZarr(refs, remote_protocol='file', xarray_concat_args={'dim': 'time'})
mz2z.translate(combined_json)

mapper = fsspec.get_mapper('reference://', fo=combined_json)

# Testing...
ds1 = zarr.open(mapper, mode='r')
%timeit ds1['U'][0,0,0,:,:]
# 401 ms ± 12.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

ds2 = xarray.open_dataset(mapper, engine='zarr')
%timeit ds2['U'][0,0,0,:,:].values
# 402 ms ± 10.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

ds3 = zarr.open('/home/idies/workspace/poseidon/data01_01/llc4320_tests/10dayhourly/velocities', mode='r')
%timeit ds3['U'][0,0,0,:,:]
# 126 ms ± 2.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

```

The three read functions at the bottom are getting a slice that fits in a single zarr chunk of one source array, so in principle it can be read directly using zarr library functions, as shown with `ds3`. But the equivalent read operation on the kerchunk combined array takes much more time (see `ds1` and `ds2`). It also takes more time than using a combined dataset produced by `xarray.open_mfdataset` (not shown here), which adds some performance overhead for using Dask, and is generally quite slow compared to pure `zarr.open` or `xarray.open_dataset`.

Is kerchunk expected to add that much overhead even when reading a single chunk from only one of the sources, or am I doing something wrong here?

**Comment by lsterzinger** [comment]
What do the speeds look like if you add `simple_templates=True` to `fsspec.filesystem('reference://'...)`? Or regenerate the combined metadata with `mz2z.translate(combined_json, templates=none)`

**Comment by dmedv** [comment]
No significant change in speed with
```python
mapper = fsspec.get_mapper('reference://', fo=combined_json, simple_templates=True)
```
Seems to be even slower by 20ms, but that's withing the margin of error, I guess.

**Comment by martindurant** [comment]
I would love to play with optimisation on your dataset and see where the bottlenecks are. A huge advantage of kerchunk/referenceFS is, that the code is very small and simple python, so we can find and fix slow paths - or just suggest better default values when building your references. The existing kerchunk timings around tend to be for remote datasets, which is what it was really built for - and never at the ms time-scale.

**Comment by dmedv** [comment]
@martindurant Thank you. The dataset has not been made public yet, but I've come up with a synthetic test that I believe illustrates the same issue:
```python
from kerchunk.zarr import single_zarr
from kerchunk.combine import MultiZarrToZarr
import fsspec
import zarr
import xarray
import numpy as np

combined_json = 'file:///home/idies/workspace/combined.json'

nx = 5000
ny = 5000
chunk_shape = (1, 10, 10)

refs = []
for i in range(1,3):
    path = f'data/example{i}.zarr'
    store = zarr.DirectoryStore(path)
    root = zarr.open_group(path, mode='w')

    t = root.zeros('t', shape=(1), chunks=(1), overwrite=True)
    x = root.zeros('x', shape=(nx), chunks=(nx), overwrite=True)
    y = root.zeros('y', shape=(ny), chunks=(ny), overwrite=True)
    t[0] = i - 1
    t.attrs['_ARRAY_DIMENSIONS'] = ['t']
    x[:] = np.arange(nx)
    x.attrs['_ARRAY_DIMENSIONS'] = ['x']
    y[:] = np.arange(ny)
    y.attrs['_ARRAY_DIMENSIONS'] = ['y']                        
    a = root.zeros('U', shape=(1, nx, ny), chunks=chunk_shape, overwrite=True)
    a[...] = np.random.rand(1, nx, ny)
    a.attrs['_ARRAY_DIMENSIONS'] = ['t','x','y']
    
    refs.append(single_zarr(path))

mz2z = MultiZarrToZarr(refs, remote_protocol='file', xarray_concat_args={'dim': 't'})
mz2z.translate(combined_json, template_count=None)

mapper = fsspec.get_mapper('reference://', fo=combined_json)

ds1 = zarr.open(mapper, mode='r')
%timeit ds1['U'][0, 0:10, 0:10]
# 494 ms ± 4.09 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

ds2 = zarr.open('data/example1.zarr', mode='r')
%timeit ds2['U'][0, 0:10, 0:10]
# 770 µs ± 5.43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

It takes a few minutes to run and will produce a fairly large reference file, about 40MB. As you can see, the performance with kerchunk in this case is also much slower than with a single zarr array. Reducing the number of chunks improves kerchunk performance and in the trivial case with a single chunk per array it becomes just as fast as reading zarr directly.

If it helps, here is the layout of our zarr arrays in the actual dataset. 
<html>
<body>


Array | Chunk
-- | --
698.72 GB | 74.65 MB
(8, 90, 13, 4320, 4320) | (1, 1, 1, 4320, 4320)
9361 Tasks | 9360 Chunks
float32 | numpy.ndarray


</body>
</html>

There are 30 such arrays distributed across 10 servers. 
The combined array shape is (240, 90, 13, 4320, 4320) and contains 280800 chunks.
The kerchunk reference file in this case also turns out quite large, over 70MB.

**Comment by martindurant** [comment]
Bottleneck found and fixed in #892 .

Note that I recommend Zstd-compressing the JSON file for big output, because it always decompresses quickly, but with great compression ration for this kind of data. It might lead to faster instantiation of the mapper even on a local disc.

**Comment by dmedv** [comment]
@rabernat I guess it's this one: https://github.com/fsspec/filesystem_spec/pull/892 I'll give it a try.

**Comment by martindurant** [comment]
Yep, sorry, copypaste failure

**Comment by dmedv** [comment]
I've tried it with the updated fsspec and can confirm that it is much faster now, comparable with reading zarr directly. Thank you, @martindurant, I appreciate the quick response.
