### ISSUE TITLE
Add these awesome bullets to readme and docs

### ISSUE THREAD

**Issue by rsignell-usgs** [fsspec/kerchunk#125]
People love bullet points, and @martindurant has some [great ones here](https://github.com/ioos/gsoc/issues/14#issuecomment-1046052472) that answer the question "why kerchunk"?

@lsterzinger and @martindurant what do you think about adding these to the readme and docs after paragraph 1?

**Comment by martindurant** [comment]
Sounds very reasonable; also for the docs at https://fsspec.github.io/kerchunk/ which starts with the same material.

**Comment by lsterzinger** [comment]
Agreed, would do well both in the readme and to the docs
