### ISSUE TITLE
Missing Coord Values and Field Data

### ISSUE THREAD

**Issue by Yefee** [fsspec/kerchunk#147]
Hello, 

Thanks for building this interesting tool! I am new to Kerchunk, and I followed the documentation to generate jsons for CESM outputs. However, I found Coord Values and Field Data are all NaN after reading in files from the json. Any thoughts are appreciated!

```
from kerchunk.hdf import SingleHdf5ToZarr 
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
import logging
import fsspec
import json
from tqdm import tqdm
from glob import glob
from ncar_jobqueue import NCARCluster
import dask

import warnings
warnings.filterwarnings("ignore")

rootdir = '/glade/scratch/che43/tmp/SLAB/T'
case = 'e.e11.E20TRLENS.ens2'
atm = 'atm/hist'
ocn = 'ocn/hist'
h = 'h0'

dirr = '/glade/scratch/che43/1dPoP/cesm2.B1850.f09_g17.1dpop.005/'
dirr = '/glade/scratch/che43/tmp/SLAB/T/'

fs = fsspec.filesystem('file', anon=True)
urls = ['file://' + f for f in fs.glob(dirr + '*.nc')]
urls
```

> ['file:///glade/scratch/che43/tmp/SLAB/T/e.e11.E20TRLENS.ens10.cam.h0.T.192001-200512.nc',
 'file:///glade/scratch/che43/tmp/SLAB/T/e.e11.E20TRLENS.ens2.cam.h0.T.192001-200512.nc',
 'file:///glade/scratch/che43/tmp/SLAB/T/e.e11.E20TRLENS.ens3.cam.h0.T.192001-200512.nc',
 'file:///glade/scratch/che43/tmp/SLAB/T/e.e11.E20TRLENS.ens4.cam.h0.T.192001-200512.nc',
 'file:///glade/scratch/che43/tmp/SLAB/T/e.e11.E20TRLENS.ens5.cam.h0.T.192001-200512.nc',
 'file:///glade/scratch/che43/tmp/SLAB/T/e.e11.E20TRLENS.ens6.cam.h0.T.192001-200512.nc',
 'file:///glade/scratch/che43/tmp/SLAB/T/e.e11.E20TRLENS.ens7.cam.h0.T.192001-200512.nc',
 'file:///glade/scratch/che43/tmp/SLAB/T/e.e11.E20TRLENS.ens8.cam.h0.T.192001-200512.nc',
 'file:///glade/scratch/che43/tmp/SLAB/T/e.e11.E20TRLENS.ens9.cam.h0.T.192001-200512.nc']

```
import ujson
def gen_json(u):
    so = dict(
        mode="rb", anon=True, default_fill_cache=False,
        default_cache_type="none"
    )
    with fsspec.open(u, **so) as inf:
        h5chunks = SingleHdf5ToZarr(inf, u, inline_threshold=300)
        with open(f"jsons/{u.split('/')[-1]}.json", 'wb') as outf:
           outf.write(ujson.dumps(h5chunks.translate()).encode())

import pathlib
pathlib.Path('./jsons/').mkdir(exist_ok=True)
dask.compute(*[dask.delayed(gen_json)(u) for u in urls])
```

```
json_list = sorted(glob("./jsons/*.T.*.json"))

m_list = []
for js in tqdm(json_list):
    with open(js) as f:
        m_list.append(fsspec.get_mapper("reference://", 
            fo=json.load(f), remote_protocol="s3",
            remote_options={"anon": True}))
m_list
```

> [<fsspec.mapping.FSMap at 0x2b2c691d1250>,
 <fsspec.mapping.FSMap at 0x2b2c3a72d910>,
 <fsspec.mapping.FSMap at 0x2b2c6915e1f0>,
 <fsspec.mapping.FSMap at 0x2b2c6915e670>,
 <fsspec.mapping.FSMap at 0x2b2c6a583a00>,
 <fsspec.mapping.FSMap at 0x2b2c6a583fa0>,
 <fsspec.mapping.FSMap at 0x2b2c6a6b76a0>,
 <fsspec.mapping.FSMap at 0x2b2c6a6b7d60>,
 <fsspec.mapping.FSMap at 0x2b2c691657f0>]

```
ds = xr.open_dataset(m_list[0], engine='zarr', decode_times=False)
ds
```
![image](https://user-images.githubusercontent.com/6420873/162824105-ec6b142f-de2c-4a27-bcd0-7b0a8eb1de08.png)

```
import kerchunk
kerchunk.__version__
```
> '0.0.6'

**Comment by martindurant** [comment]
You usually get spurious NaNs when the target filesystem is not finding the original files, which to zarr looks like a missing key. I advise you turn on the logger: `fsspec.utils.setup_logging(logger_name="fsspec.reference")` to figure out what file it's trying to get and why it might be failing. If there is something special about the files, I wouldn't be able to tell from your code, I would need to look at at least one of the files myself.

**Comment by rsignell-usgs** [comment]
Note also you can take a peek at the "files" in the referenceFileSystem and sometimes figure out what's wrong.
We had a case that was coming back NaNs and it was because the NetCDF files were in a directory `<>/nc/nc/*.nc` when the references were made, but then the files were moved to `<>/nc/*.nc`, and of course the references didn't point to them any more:
```
fs_ref.cat('x/0') -> FileNotFound (NoSuchKey)
fs_ref.references['x/0'] -> ['s3://nhgf-development/lcmap/nc/nc/LCMAP_CU_1985_V12_LCPRI.nc', 1065, 1280000]

fs_s3.cat('s3://nhgf-development/lcmap/nc/nc/LCMAP_CU_1985_V12_LCPRI.nc', 1065, 1280000) -> FileNotFound
```

**Comment by Yefee** [comment]
> You usually get spurious NaNs when the target filesystem is not finding the original files, which to zarr looks like a missing key. I advise you turn on the logger: `fsspec.utils.setup_logging(logger_name="fsspec.reference")` to figure out what file it's trying to get and why it might be failing. If there is something special about the files, I wouldn't be able to tell from your code, I would need to look at at least one of the files myself.

Thanks for the reply! @martindurant @rsignell-usgs 

I turned on the debug mode and the results are below.

This [link](https://drive.google.com/drive/folders/1Rxr9XsCu3A69d_L8B9wYLMaf3qEa00zd?usp=sharing) contains a sample file and associated json. If you could take a look, it would be greatly appreciated!

```
ds = xr.open_dataset(m_list[0], engine='zarr', decode_times=False)
ds
```

> 2022-04-15 08:21:26,648 - fsspec.reference - DEBUG - _cat_common -- cat: .zmetadata
/glade/scratch/che43/ipykernel_165783/3569108847.py:1: RuntimeWarning: Failed to open Zarr store with consolidated metadata, falling back to try reading non-consolidated metadata. This is typically much slower for opening a dataset. To silence this warning, consider:

> 1. Consolidating metadata in this existing store with zarr.consolidate_metadata().
> 2. Explicitly setting consolidated=False, to avoid trying to read consolidate metadata, or
> 3. Explicitly setting consolidated=True, to raise an error in this case instead of falling back to try reading non-consolidated metadata.

>   ds = xr.open_dataset(m_list[0], engine='zarr', decode_times=False)
> 2022-04-15 08:21:26,649 - fsspec.reference - DEBUG - _cat_common -- cat: .zgroup
> 2022-04-15 08:21:26,649 - fsspec.reference - DEBUG - _cat_common -- Reference: .zgroup, type bytes
> 2022-04-15 08:21:26,649 - fsspec.reference - DEBUG - _cat_common -- cat: .zarray
> 2022-04-15 08:21:26,650 - fsspec.reference - DEBUG - _cat_common -- cat: .zgroup
> 2022-04-15 08:21:26,650 - fsspec.reference - DEBUG - _cat_common -- Reference: .zgroup, type bytes
> 2022-04-15 08:21:26,651 - fsspec.reference - DEBUG - _cat_common -- cat: .zattrs/.zarray
> 2022-04-15 08:21:26,652 - fsspec.reference - DEBUG - _cat_common -- cat: .zgroup/.zarray
> 2022-04-15 08:21:26,652 - fsspec.reference - DEBUG - _cat_common -- cat: TS/.zarray
> 2022-04-15 08:21:26,652 - fsspec.reference - DEBUG - _cat_common -- Reference: TS/.zarray, type bytes
> 2022-04-15 08:21:26,653 - fsspec.reference - DEBUG - _cat_common -- cat: TS/.zarray
> 2022-04-15 08:21:26,653 - fsspec.reference - DEBUG - _cat_common -- Reference: TS/.zarray, type bytes
> 2022-04-15 08:21:26,653 - fsspec.reference - DEBUG - _cat_common -- cat: TS/.zarray
> 2022-04-15 08:21:26,653 - fsspec.reference - DEBUG - _cat_common -- Reference: TS/.zarray, type bytes
> 2022-04-15 08:21:26,654 - fsspec.reference - DEBUG - _cat_common -- cat: TS/.zarray
> 2022-04-15 08:21:26,654 - fsspec.reference - DEBUG - _cat_common -- Reference: TS/.zarray, type bytes
> 2022-04-15 08:21:26,654 - fsspec.reference - DEBUG - _cat_common -- cat: TS/.zarray
> 2022-04-15 08:21:26,655 - fsspec.reference - DEBUG - _cat_common -- Reference: TS/.zarray, type bytes
> 2022-04-15 08:21:26,655 - fsspec.reference - DEBUG - _cat_common -- cat: TS/.zattrs
> 2022-04-15 08:21:26,655 - fsspec.reference - DEBUG - _cat_common -- Reference: TS/.zattrs, type bytes
> 2022-04-15 08:21:26,656 - fsspec.reference - DEBUG - _cat_common -- cat: lat/.zarray
> 2022-04-15 08:21:26,656 - fsspec.reference - DEBUG - _cat_common -- Reference: lat/.zarray, type bytes
> 2022-04-15 08:21:26,656 - fsspec.reference - DEBUG - _cat_common -- cat: lat/.zarray
> 2022-04-15 08:21:26,656 - fsspec.reference - DEBUG - _cat_common -- Reference: lat/.zarray, type bytes
> 2022-04-15 08:21:26,657 - fsspec.reference - DEBUG - _cat_common -- cat: lat/.zarray
> 2022-04-15 08:21:26,657 - fsspec.reference - DEBUG - _cat_common -- Reference: lat/.zarray, type bytes
> 2022-04-15 08:21:26,657 - fsspec.reference - DEBUG - _cat_common -- cat: lat/.zarray
> 2022-04-15 08:21:26,658 - fsspec.reference - DEBUG - _cat_common -- Reference: lat/.zarray, type bytes
> 2022-04-15 08:21:26,658 - fsspec.reference - DEBUG - _cat_common -- cat: lat/.zarray
> 2022-04-15 08:21:26,658 - fsspec.reference - DEBUG - _cat_common -- Reference: lat/.zarray, type bytes
> 2022-04-15 08:21:26,658 - fsspec.reference - DEBUG - _cat_common -- cat: lat/.zattrs
> 2022-04-15 08:21:26,659 - fsspec.reference - DEBUG - _cat_common -- Reference: lat/.zattrs, type bytes
> 2022-04-15 08:21:26,659 - fsspec.reference - DEBUG - _cat_common -- cat: lon/.zarray
> 2022-04-15 08:21:26,659 - fsspec.reference - DEBUG - _cat_common -- Reference: lon/.zarray, type bytes
> 2022-04-15 08:21:26,660 - fsspec.reference - DEBUG - _cat_common -- cat: lon/.zarray
> 2022-04-15 08:21:26,660 - fsspec.reference - DEBUG - _cat_common -- Reference: lon/.zarray, type bytes
> 2022-04-15 08:21:26,660 - fsspec.reference - DEBUG - _cat_common -- cat: lon/.zarray
> 2022-04-15 08:21:26,660 - fsspec.reference - DEBUG - _cat_common -- Reference: lon/.zarray, type bytes
> 2022-04-15 08:21:26,661 - fsspec.reference - DEBUG - _cat_common -- cat: lon/.zarray
> 2022-04-15 08:21:26,661 - fsspec.reference - DEBUG - _cat_common -- Reference: lon/.zarray, type bytes
> 2022-04-15 08:21:26,661 - fsspec.reference - DEBUG - _cat_common -- cat: lon/.zarray
> 2022-04-15 08:21:26,661 - fsspec.reference - DEBUG - _cat_common -- Reference: lon/.zarray, type bytes
> 2022-04-15 08:21:26,662 - fsspec.reference - DEBUG - _cat_common -- cat: lon/.zattrs
> 2022-04-15 08:21:26,662 - fsspec.reference - DEBUG - _cat_common -- Reference: lon/.zattrs, type bytes
> 2022-04-15 08:21:26,662 - fsspec.reference - DEBUG - _cat_common -- cat: time/.zarray
> 2022-04-15 08:21:26,663 - fsspec.reference - DEBUG - _cat_common -- Reference: time/.zarray, type bytes
> 2022-04-15 08:21:26,663 - fsspec.reference - DEBUG - _cat_common -- cat: time/.zarray
> 2022-04-15 08:21:26,663 - fsspec.reference - DEBUG - _cat_common -- Reference: time/.zarray, type bytes
> 2022-04-15 08:21:26,663 - fsspec.reference - DEBUG - _cat_common -- cat: time/.zarray
> 2022-04-15 08:21:26,664 - fsspec.reference - DEBUG - _cat_common -- Reference: time/.zarray, type bytes
> 2022-04-15 08:21:26,664 - fsspec.reference - DEBUG - _cat_common -- cat: time/.zarray
> 2022-04-15 08:21:26,664 - fsspec.reference - DEBUG - _cat_common -- Reference: time/.zarray, type bytes
> 2022-04-15 08:21:26,665 - fsspec.reference - DEBUG - _cat_common -- cat: time/.zarray
> 2022-04-15 08:21:26,665 - fsspec.reference - DEBUG - _cat_common -- Reference: time/.zarray, type bytes
> 2022-04-15 08:21:26,665 - fsspec.reference - DEBUG - _cat_common -- cat: time/.zattrs
> 2022-04-15 08:21:26,665 - fsspec.reference - DEBUG - _cat_common -- Reference: time/.zattrs, type bytes
> 2022-04-15 08:21:26,666 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/.zarray
> 2022-04-15 08:21:26,666 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/.zarray, type bytes
> 2022-04-15 08:21:26,666 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/.zarray
> 2022-04-15 08:21:26,667 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/.zarray, type bytes
> 2022-04-15 08:21:26,667 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/.zarray
> 2022-04-15 08:21:26,667 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/.zarray, type bytes
> 2022-04-15 08:21:26,668 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/.zarray
> 2022-04-15 08:21:26,668 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/.zarray, type bytes
> 2022-04-15 08:21:26,668 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/.zarray
> 2022-04-15 08:21:26,668 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/.zarray, type bytes
> 2022-04-15 08:21:26,669 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/.zattrs
> 2022-04-15 08:21:26,669 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/.zattrs, type bytes
> 2022-04-15 08:21:26,669 - fsspec.reference - DEBUG - _cat_common -- cat: .zattrs
> 2022-04-15 08:21:26,670 - fsspec.reference - DEBUG - _cat_common -- Reference: .zattrs, type bytes
> 2022-04-15 08:21:26,671 - fsspec.reference - DEBUG - _cat_common -- cat: lat/.zarray
> 2022-04-15 08:21:26,674 - fsspec.reference - DEBUG - _cat_common -- Reference: lat/.zarray, type bytes
> 2022-04-15 08:21:26,674 - fsspec.reference - DEBUG - _cat_common -- cat: lat/.zarray
> 2022-04-15 08:21:26,675 - fsspec.reference - DEBUG - _cat_common -- Reference: lat/.zarray, type bytes
> 2022-04-15 08:21:26,675 - fsspec.reference - DEBUG - _cat_common -- cat: lon/.zarray
> 2022-04-15 08:21:26,676 - fsspec.reference - DEBUG - _cat_common -- Reference: lon/.zarray, type bytes
> 2022-04-15 08:21:26,676 - fsspec.reference - DEBUG - _cat_common -- cat: lon/.zarray
> 2022-04-15 08:21:26,676 - fsspec.reference - DEBUG - _cat_common -- Reference: lon/.zarray, type bytes
> 2022-04-15 08:21:26,677 - fsspec.reference - DEBUG - _cat_common -- cat: time/.zarray
> 2022-04-15 08:21:26,677 - fsspec.reference - DEBUG - _cat_common -- Reference: time/.zarray, type bytes
> 2022-04-15 08:21:26,678 - fsspec.reference - DEBUG - _cat_common -- cat: time/.zarray
> 2022-04-15 08:21:26,678 - fsspec.reference - DEBUG - _cat_common -- Reference: time/.zarray, type bytes
> 2022-04-15 08:21:26,678 - fsspec.reference - DEBUG - _cat_common -- cat: time/2
> 2022-04-15 08:21:26,679 - fsspec.reference - DEBUG - _cat_common -- Reference: time/2, type bytes
> 2022-04-15 08:21:26,687 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/.zarray
> 2022-04-15 08:21:26,688 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/.zarray, type bytes
> 2022-04-15 08:21:26,688 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/.zarray
> 2022-04-15 08:21:26,688 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/.zarray, type bytes
> 2022-04-15 08:21:26,690 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/0.0
> 2022-04-15 08:21:26,691 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/0.0, type bytes
> 2022-04-15 08:21:26,691 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/1.0
> 2022-04-15 08:21:26,691 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/1.0, type bytes
> 2022-04-15 08:21:26,692 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/2.0
> 2022-04-15 08:21:26,692 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/2.0, type bytes
> 2022-04-15 08:21:26,693 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/3.0
> 2022-04-15 08:21:26,693 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/3.0, type bytes
> 2022-04-15 08:21:26,693 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/4.0
> 2022-04-15 08:21:26,694 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/4.0, type bytes
> 2022-04-15 08:21:26,694 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/5.0
> 2022-04-15 08:21:26,694 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/5.0, type bytes
> 2022-04-15 08:21:26,694 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/6.0
> 2022-04-15 08:21:26,695 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/6.0, type bytes
> 2022-04-15 08:21:26,695 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/7.0
> 2022-04-15 08:21:26,695 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/7.0, type bytes
> 2022-04-15 08:21:26,696 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/8.0
> 2022-04-15 08:21:26,696 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/8.0, type bytes
> 2022-04-15 08:21:26,696 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/9.0
> 2022-04-15 08:21:26,697 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/9.0, type bytes
> 2022-04-15 08:21:26,697 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/10.0
> 2022-04-15 08:21:26,697 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/10.0, type bytes
> 2022-04-15 08:21:26,697 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/11.0
> 2022-04-15 08:21:26,698 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/11.0, type bytes
> 2022-04-15 08:21:26,698 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/12.0
> 2022-04-15 08:21:26,698 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/12.0, type bytes
> 2022-04-15 08:21:26,699 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/13.0
> 2022-04-15 08:21:26,699 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/13.0, type bytes
> 2022-04-15 08:21:26,699 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/14.0
> 2022-04-15 08:21:26,700 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/14.0, type bytes
> 2022-04-15 08:21:26,700 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/15.0
> 2022-04-15 08:21:26,700 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/15.0, type bytes
> 2022-04-15 08:21:26,700 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/16.0
> 2022-04-15 08:21:26,701 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/16.0, type bytes
> 2022-04-15 08:21:26,701 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/17.0
> 2022-04-15 08:21:26,701 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/17.0, type bytes
> 2022-04-15 08:21:26,702 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/18.0
> 2022-04-15 08:21:26,702 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/18.0, type bytes
> 2022-04-15 08:21:26,702 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/19.0
> 2022-04-15 08:21:26,702 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/19.0, type bytes
> 2022-04-15 08:21:26,703 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/20.0
> 2022-04-15 08:21:26,703 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/20.0, type bytes
> 2022-04-15 08:21:26,703 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/21.0
> ...

> 2022-04-15 08:21:27,375 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/1028.0, type bytes
> 2022-04-15 08:21:27,376 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/1029.0
> 2022-04-15 08:21:27,377 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/1029.0, type bytes
> 2022-04-15 08:21:27,377 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/1030.0
> 2022-04-15 08:21:27,377 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/1030.0, type bytes
> 2022-04-15 08:21:27,378 - fsspec.reference - DEBUG - _cat_common -- cat: time_bnds/1031.0
> 2022-04-15 08:21:27,378 - fsspec.reference - DEBUG - _cat_common -- Reference: time_bnds/1031.0, type bytes



```
ds.TS.values
```

> 2022-04-15 08:24:13,433 - fsspec.reference - DEBUG - _cat_common -- cat: TS/.zarray
> 2022-04-15 08:24:13,434 - fsspec.reference - DEBUG - _cat_common -- Reference: TS/.zarray, type bytes
> 2022-04-15 08:24:13,435 - fsspec.reference - DEBUG - _cat_common -- cat: TS/.zarray
> 2022-04-15 08:24:13,435 - fsspec.reference - DEBUG - _cat_common -- Reference: TS/.zarray, type bytes
> array([[[nan, nan, nan, ..., nan, nan, nan],
>         [nan, nan, nan, ..., nan, nan, nan],
>         [nan, nan, nan, ..., nan, nan, nan],
>         ...,
>         [nan, nan, nan, ..., nan, nan, nan],
>         [nan, nan, nan, ..., nan, nan, nan],
>         [nan, nan, nan, ..., nan, nan, nan]],
> 
>        [[nan, nan, nan, ..., nan, nan, nan],
>         [nan, nan, nan, ..., nan, nan, nan],
>         [nan, nan, nan, ..., nan, nan, nan],
>         ...,
>         [nan, nan, nan, ..., nan, nan, nan],
>         [nan, nan, nan, ..., nan, nan, nan],
>         [nan, nan, nan, ..., nan, nan, nan]],

**Comment by rsignell-usgs** [comment]
@martindurant I can take a look at this file, unless you already have!

**Comment by martindurant** [comment]
I haven't yet

**Comment by rsignell-usgs** [comment]
The test file worked fine for me!
https://nbviewer.org/gist/e9469984e3932f9a58e9a4eef2efbd9e

**Comment by Yefee** [comment]
@rsignell-usgs Thanks so much! I found the mistake now. It is because I am not familiar with the fessec file system.


Change the _remote_protocol="s3"_ to _remote_protocol="file"_ in the below snippet would make it work!
```
json_list = sorted(glob("./jsons/*.T.*.json"))

m_list = []
for js in tqdm(json_list):
    with open(js) as f:
        m_list.append(fsspec.get_mapper("reference://", 
            fo=json.load(f), remote_protocol="s3",
            remote_options={"anon": True}))
```

Thanks again!

**Comment by rsignell-usgs** [comment]
@Yefee great!
