### ISSUE TITLE
Issue reading zarr files with Dask distributed

### ISSUE THREAD

**Issue by dmcg** [fsspec/kerchunk#153]
I'm not at all sure that this is kerchunk's problem to be honest, but would welcome a pointer.

I can kerchunk UK Met Office netCDF files and read them into xarray as zarr, but if I try to read them with Dask workers they all read until they have run out of memory and crash.

```
import dask
from dask.distributed import Client
client = Client()

import fsspec
import xarray

def open_fsspec_zarr(json_path):
    with open(json_path) as f:
        mapper = fsspec.get_mapper(
                "reference://", 
                fo=json.load(f),
                remote_protocol="s3",
                remote_options={"anon": False})
        return xarray.open_dataset(mapper, engine='zarr', consolidated=False)
```    

If we don't chunk the dataset, it works

```
dataset = open_fsspec_zarr('/data/metoffice/000490262cdd067721a34112963bcaa2b44860ab.json')

%%time
slice = dataset.isel(height=5, realization=1)
slice

CPU times: user 659 µs, sys: 0 ns, total: 659 µs
Wall time: 636 µs

<xarray.Dataset>
Dimensions:                  (latitude: 960, longitude: 1280, bnds: 2)
Coordinates:
    forecast_period          timedelta64[ns] 1 days 18:00:00
    forecast_reference_time  datetime64[ns] 2021-11-07T06:00:00
    height                   float32 75.0
  * latitude                 (latitude) float32 -89.91 -89.72 ... 89.72 89.91
  * longitude                (longitude) float32 -179.9 -179.6 ... 179.6 179.9
    realization              float64 18.0
    time                     datetime64[ns] 2021-11-09
Dimensions without coordinates: bnds
Data variables:
    air_pressure             (latitude, longitude) float32 ...
    latitude_bnds            (latitude, bnds) float32 -90.0 -89.81 ... 90.0
    latitude_longitude       float64 nan
    longitude_bnds           (longitude, bnds) float32 -180.0 -179.7 ... 180.0
Attributes:
    Conventions:                  CF-1.7
    history:                      2021-11-07T10:27:38Z: StaGE Decoupler
    institution:                  Met Office
    least_significant_digit:      1
    mosg__forecast_run_duration:  PT198H
    mosg__grid_domain:            global
    mosg__grid_type:              standard
    mosg__grid_version:           1.6.0
    mosg__model_configuration:    gl_ens
    source:                       Met Office Unified Model
    title:                        MOGREPS-G Model Forecast on Global 20 km St...
    um_version:                   11.5

%time
fetched_slice = slice.to_array()[0,...,0]
plt.figure(figsize=(6, 6))
plt.imshow(fetched_slice, origin='lower')    

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.72 µs

<matplotlib.image.AxesImage at 0x7f4608324550>
```

If we chunk it, it is run on the Dask workers, but runs out of memory on the workers and crashes the whole box.

```
chunked_dataset = dataset.chunk('auto')

%%time
slice = chunked_dataset.isel(height=5, realization=1)
slice

%time
fetched_slice = slice.to_array()[0,...,0]
plt.figure(figsize=(6, 6))
plt.imshow(fetched_slice, origin='lower')    
```

My assumption is that the reference filesystem is not being properly communicated to the workers as a task graph?

**Comment by rsignell-usgs** [comment]
@dmcg, I think the problem is you are asking for a rechunking when you do chunk('auto').  Usually what you want is to use the chunking you already have in the virtual zarr dataset.   You can achieve this by just adding `chunks={}` when you open the dataset. 

So try:
```python
def open_fsspec_zarr(json_path):
    with open(json_path) as f:
        mapper = fsspec.get_mapper(
                "reference://", 
                fo=json.load(f),
                remote_protocol="s3",
                remote_options={"anon": False})
        return xarray.open_dataset(mapper, engine='zarr', chunks={}, backend_kwargs=dict(consolidated=False))
```

**Comment by dmcg** [comment]
Ah, that makes a lot of sense, thanks...

... but leads to another issue, sigh. 

The source netCDF files don't have any chunking (or rather, have one big chunk). When I open those locally with `xarray.open_dataset('/data/metoffice/000490262cdd067721a34112963bcaa2b44860ab.nc').chunk('auto')` I get 5x4 chunks of lat, long, each 18 realisations and 33 heights. 

These are successfully processed by workers without using too much memory. I assume each has to read the whole source chunk (or at least as far as is required to find its processing chunk), but can discard the bytes it doesn't need.

Maybe the zarr reading is not discarding the surplus data bytes but hanging onto them - perhaps this is s3fs?

**Comment by martindurant** [comment]
zarr and s3fs should be pretty good at reading exactly the chunks of bytes it needs and then discarding. While processing, you would expect to see memory spikes as the bytes are uncompressed and converted into internal representation, plus any temporaries that the task requires.

**Comment by rsignell-usgs** [comment]
@dmcg, Can you report back on what this produces?
```python
ds = xarray.open_dataset('/data/metoffice/000490262cdd067721a34112963bcaa2b44860ab.nc')
ds.data_vars[0].encoding
```

**Comment by rsignell-usgs** [comment]
@dmcg , darn.  Indeed.  No chunking.

**Comment by dmcg** [comment]
When I run the code with `chunks={}` but without a Dask client in scope it runs sucessfully in the jupyter server process, but peaks at about 3GiB. I suspect that if I give the workers that amount of memory it might complete distributed, but if so it does suggest that they aren't discarding much of the 2.7GiB of data when they process their chunks?

**Comment by rsignell-usgs** [comment]
Each chunk *is* 3GB: 
```
realization = 18 ;
height = 33 ;
latitude = 960 ;
longitude = 1280 ;
print(realization*height*latitude*longitude*4/1e9)   #chunk of 4byte floats in GB
2.9

**Comment by rsignell-usgs** [comment]
@martindurant ooh!  So in other words we could split these files in 18*33 chunks, or 9*33 chunks, etc, right?

**Comment by martindurant** [comment]
Yes, totally possible. I already had that in mind for netCDF3, which is not compressed internally and has that awkward "append" dimension. I didn't expect to find uncompressed netCDF4/HDF.

Separately, there is also a idea that zarr should pass on the exact request to the storage layer in the case of no compression or compatible block-wise compression, such that you don't need to load whole chunks. That would need development in zarr, so a larger undertaking but more universally useful.

**Comment by martindurant** [comment]
Not arbitrary chunks: for original [ 18, 33, 960, 1280 ], you could have chunks
- [ 9, 33, 960, 1280 ]
- [ 6, 33, 960, 1280 ]
- [ 3, 33, 960, 1280 ]
- [ 1, 33, 960, 1280 ]
- [ 1, 11, 960, 1280 ]
- [ 1, 3, 960, 1280 ]

**Comment by dmcg** [comment]
Am I right in thinking though that _something_ in the workers must be holding on to data that they don't require to be processing their current chunk, even discounting the fact that they could just do some sums and set range headers?

**Comment by dmcg** [comment]
Thanks for your help. When I'm feeling brave I'll try hand-editing the kerchunk .json file to represent the source as multiple chunks.

**Comment by martindurant** [comment]
> Am I right in thinking though that something in the workers must be holding on to data that they don't require to be processing their current chunk, even discounting the fact that they could just do some sums and set range headers?

They need the 3GB of bytes and then an in-memory representation of the data. There is no way to get only part of this as things stand (until you edit the refs file!).

To edit, you will need to change the chunking in the .zarray file, and edit and add keys. So for air_pressure, you would edit key "air_pressure/.zarray"'s chunks: field, and lookgin at the "air_pressure/0.0.0.0" file, you will see a [URL, offset, size] as the value. You will want to make keys like "air_pressure/i.0.0.0" with i from 0 to 17 (let's suppose you choose chunking of [ 1, 33, 960, 1280 ]), with each having offset of i*size compared to the original offset. You can edit just the one variable before trying others.

**Comment by rsignell-usgs** [comment]
@dmcg if you succeed with the hand editing, please report back!   That would be super cool, and a kerchunk first!
We have special prizes for that, right @martindurant ?  🙃

**Comment by dmcg** [comment]
> They need the 3GB of bytes and then an in-memory representation of the data. There is no way to get only part of this as things stand (until you edit the refs file!).

This is the bit that I don't understand. Running the same 'algorithm' against the netCDF file 

```
dataset = xarray.open_dataset('/data/metoffice/000490262cdd067721a34112963bcaa2b44860ab.nc').chunk('auto')
dataset

  | Array | Chunk
-- | -- | --
2.72 GiB | 69.61 MiB
(18, 33, 960, 1280) | (18, 33, 192, 160)
41 Tasks | 40 Chunks
float32 | numpy.ndarray

slice = dataset.isel(height=5, realization=1)
fetched_slice = slice.to_array()[0,...,0]
```

gives very little memory used per worker. My model was that, even if there had been compression, each could have read and decompressed the entire file, discarding all but the bytes that needed to be assembled to represent their current chunk. With no compression, each could just seek in the file to find the bits of the chunk? Is there any reason why zarr cannot assemble the xarray chunks in the same way?

**Comment by rsignell-usgs** [comment]
If you have very little memory used on each worker when you do `chunk('auto')` then I guess it *must* be using byte ranges to extract subchunks from each chunk, right @martindurant ?

**Comment by martindurant** [comment]
I don't know, this is up to the netCDF driver.

**Comment by dmcg** [comment]
I really appreciate the help, and at least am more convinced that if there is an issue, it is with zarr reading not kerchunk writing.

**Comment by martindurant** [comment]
Well done! What is especially interesting here, is that you can do this "rechunking" after originally creating the references without any need to rescan the original file or add additional arguments.

Agreed that we wouldn't normally want people to attempt this kind of thing themselves, code ought to be better at being systematically correct :)

**Comment by NikosAlexandris** [comment]
> Not arbitrary chunks: for original [ 18, 33, 960, 1280 ], you could have chunks
> 
>     * [ 9, 33, 960, 1280 ]
> 
>     * [ 6, 33, 960, 1280 ]
> 
>     * [ 3, 33, 960, 1280 ]
> 
>     * [ 1, 33, 960, 1280 ]
> 
>     * [ 1, 11, 960, 1280 ]
> 
>     * [ 1, 3, 960, 1280 ]

What other _algorithms_ suggesting a good chunking shape for time series are out there? Can we roughly group some common read access patterns and come up with some recommendations? Or wouldn't it make sense to attempt listing some common use-cases?

**Comment by martindurant** [comment]
> What other algorithms suggesting a good chunking shape for time series are out there?

My list is complete (except even smaller chunks), these are the only possible ways to subchunk the original, given that chunks must be contiguous. If you are however rechunking, then you want something matching the fuzzy statement:
- as big as comfortably fits in memory, particularly along the axis(es) of interest.

Where "comfort" depends on what exactly the process is doing.

**Comment by NikosAlexandris** [comment]
> > What other algorithms suggesting a good chunking shape for time series are out there?
> 
> My list is complete (except even smaller chunks), these are the only possible ways to subchunk the original, given that chunks must be contiguous. If you are however rechunking, then you want something matching the fuzzy statement:
> 
>     * as big as comfortably fits in memory, particularly along the axis(es) of interest.
> 
> 
> Where "comfort" depends on what exactly the process is doing.

Would you consider sizes that are multiples (or let me call it _compatible_!) of the file system's physical block size?

**Comment by martindurant** [comment]
> Would you consider sizes that are multiples (or let me call it compatible!) of the file system's physical block size?
