### ISSUE TITLE
MultiZarrToZarr.translate() output JSONs from NetCDFs exponentially larger than from GRIBs

### ISSUE THREAD

**Issue by rbanick** [fsspec/kerchunk#156]
I'm new to the world of Kerchunk, fsspec, and even Pangeo so apologies in advance if this question is redundant / easily resolved.

I need to download, rearrange (rechunk), and parse out climate datasets in many formats from many providers. Kerchunk seems like an excellent tool to speed up some of these steps so I've been digging into its particulars for different datasets. Note that because many such datasets are not offered in modern cloud environments my base case is processing locally downloaded files -- although remote usage is definitely a future use case.

### Problem
I've noticed an exponential difference in the file sizes of local JSON outputs returned by `kerchunk.combine.translate()` when feeding it `MultiZarrToZarr` objects generated from collections of NetCDFs (`kerchunk.hdf.SingleHDF5ToZarr`) and GRIBs (`kerchunk.grb2.scan_grib`). In an example case, reading in the same dataset prepared into collections of 900 NetCDF4 (Classic) and GRIB2 files, each 21.5 and ~7 MB respectivly, results in local master Zarr JSON files of 27.93GB and 132 KB, respectively. The write times for these differ considerably as well. I need to scale my work to potentially hundreds of thousands of input NetCDF files at some point so this is problematic.

Looking into the generated JSONs, it appears that `SingleHDF5ToZarr` is reading and outputting the array values for each NetCDF as very long `base64` encoded strings, whereas `scan_grib` is returning `[{{url}},(byte_range)]`. I would have anticipated that NetCDF returns a URL and byte_range as well, based on my understanding of what `fsspec` is doing under the hood. See below example snippets:

**NetCDF**
```
time\/0":"base64:AAAAAAAAOEAAAAAAAAA5QAAAAAAAADpAAAAAAA }",AAO0AAAAAAAAA8QA... # this continues onward for a long, long time
```
**GRIB**
```
"t2m\/1.0.0":["/path/to/file/2tm_19920101_1.grib1",0,1660944320] # nice and tidy
```

How can I instruct `kerchunk.hdf.SingleHDF5ToZarr` to output `[{{url}},(byte_range)]` for data arrays instead of `base64` strings? Is this something that can be specific in the input `storage_options`? Any help appreciated.

### Example

A minimal example of how these have been prepared follows, using kerchunk `0.0.06` and fsspec `2022.3.0`

Note that I have to output the individual NetCDF kerchunk files as JSONs (34 KB each) because dealing with them in memory causes `MultiZarrToZarr` to fail on some hard-to-diganose issues with how the JSONs are represented (which is an interesting but separate issue).

**NetCDF**
```
files_list = list(glob.glob("netcdf/dir/*.nc"))
fs = fsspec.filesystem('file')
so = dict(protocol='file', mode="rb", default_fill_cache=False, default_cache_type="first")
for input_nc in files_list:
    with fs.open(input_nc, **so) as infile:
        h5chunks = kerchunk.hdf.SingleHdf5ToZarr(infile, input_nc, inline_threshold=100)
        with open(f"temp/parse/individual_jsons/{os.path.basename(input_nc)}.json", 'wb') as out_file:
            out_file.write(ujson.dumps(h5chunks.translate()).encode())

netcdf_zarr_jsons = []
nc_jsons = list(glob.glob("temp/parse/individual_jsons/*.json"))
for nc_json in nc_jsons:
    with open(nc_json, 'rb') as json_bin:
        mem_json = fsspec.get_mapper("reference://",
                                  fo = ujson.load(json_bin),
                                  remote_protocol = 'file',
                                  remote_options = {"anon": True})
        netcdf_zarr_jsons.append(mem_json)

mzz = MultiZarrToZarr(netcdf_zarr_jsons,
                        remote_protocol = 'file',
                        identical_dims = ["lon"],
                        concat_dims = ["lat"])
mzz.translate(filename='/path/to/final/zarrs/final_zarr_nc.json')
```

**GRIB**
```
files_list = list(glob.glob("grib/dir/*.grib1"))
grib_zarr_jsons = []

so = {"anon": True, "default_fill_cache":"False", "default_cache_type": "none"}
for input_grib in files_list:
    result = kerchunk.grb2.scan_grib(input_grib, common_vars=["lat","lon","valid_time"], storage_options=so)
    grib_zarr_jsons.append(result)
grib_zarr_jsons = list(grib_zarr_jsons)

mzz = MultiZarrToZarr(grib_zarr_jsons,
                        remote_protocol = 'file',
                        identical_dims = ["longitude"],
                        postprocess = kerchunk.combine.drop(['time','step']),
                        concat_dims = ["valid_time"])
mzz.translate(filename='/path/to/final/zarrs/final_zarr_grib.json')
```

### Replicating

I have uploaded 5 copies of the data as GRIB1s and NetCDFs to the below folder. Note this data is originally ERA5 Land 2m Temperature data that I have pre-processed to get closer to my desired final chunk size and shape. Right now they hold a month's worth of time step values, stacked into one dimension, for 2 latitudes each.

https://drive.google.com/drive/folders/1EAaT6vy-NHdp_xcDYf5ssDvli9Ayp4_n?usp=sharing

### En Fin

Thanks for any help you can give! I really appreciate the hard work put into Kerchunk so far.

**Comment by martindurant** [comment]
I am finding 34kb for the references of the first .nc file, 758 keys and only 3 keys < 100bytes (most 28,800bytes). Does that sound right?

**Comment by rbanick** [comment]
That sounds right, yep. The references for all .nc files generated on my side are 34KB as well.

**Comment by martindurant** [comment]
The length of the combined json I am seeing at 435kb for the 5 files. This seems linear, except that the individual references have had "{{u}}" expanded to their actual (local) path.

> "t2m\/1.0.0":["/path/to/file/2tm_19920101_1.grib1",0,1660944320]

This is much bigger than the entire file?? Actually - this is GRIB1 not GRIB2, that might be the fundamental problem.

**Comment by rbanick** [comment]
The problem is with the NetCDFs, not the GRIBs! 435kb is just fine for a GRIB output but if you run the code on the NetCDFs you should see a very large combined json.

**Comment by rbanick** [comment]
I’d be interested to hear what quirks / problems to be aware of vis-a-vis GRIB1s however — I had to patch line 22 of `grib2.py` to read `assert ((data[:4] == b"GRIB") | (data[:5] == b"GRIBO"))` instead of `assert data[-4:] == b"7777"` to correctly read in GRIB1s. I was mildly surprised that things worked after that small fix, to be honest.

**Comment by martindurant** [comment]
435kb is what I got for the .nc files (five of them). I was not able to process GRIB at all :|

**Comment by martindurant** [comment]
I hadn't even tried GRIB1 ever, I don't know the difference. The size of the chunk in that example reference is obviously wrong, but if each file has exactly one grib chunk, maybe it doesn't matter.

**Comment by rbanick** [comment]
Oh curious that that’s what you got with .ncs. I’m running kerchunk `0.0.06` and fsspec `2022.3.0` — same on your side? Amended my initial post to include this info.

**Comment by rbanick** [comment]
> Actually - this is GRIB1 not GRIB2, that might be the fundamental problem.

To understand correctly — are you suggesting that translating from GRIB1 to NC may be the fundamental problem? I can explore an intermediate transform to GRIB2 if so.

**Comment by martindurant** [comment]
```
In [69]: kerchunk.__version__
Out[69]: '0.0.6+22.g55d93e9.dirty'
```
(main branch)

```
for of in fsspec.open_files("*.nc"):
   with of as f:
     # not writing intermediaries, but that won't matter
     outs.append(kerchunk.hdf.SingleHdf5ToZarr(f, of.path).translate())

mzz = kerchunk.combine.MultiZarrToZarr(outs, identical_dims=["lon"], concat_dims=["lat"])
out = mzz.translate()
len(ujson.dumps(out)) # -> 435323
```
The exact size for s3 will be a little different, since the full paths are embedded in the file.

> To understand correctly — are you suggesting that translating from GRIB1 to NC may be the fundamental problem? I can explore an intermediate transform to GRIB2 if so, and report back for thoroughness’ sake.

No, I'm suggesting that scan_grib is doing the wrong thing, and it just happens to work out for this case by treating the whole file as a single chunk (presumably cfgrib can read both grib1 and grib2). I imagine if you did want to try transforming to GRIB2 and run scan_grib on that, you would get the same chunking and same size references file as for the .nc case.

**Comment by rbanick** [comment]
Understood about GRIBs, I’ll look into that on my side.

Regarding NCs, I’m able to approximately replicate your results **if I do not write intermediary files**. This solves my problem but let’s dig a little deeper for learning’s sake.

Looking at the intermediate files generated for `.nc` inputs now with a keener eye towards offsets (example [here](https://gist.github.com/rbanick/9a9cd1b3c85e5739dbf6dfff358c3bed)) it looks to me like the offsets provided for each key are much, much larger than the actual length. An example would be 
```"var167\/158.0.0":["{{u}}",4609580,28800]```

Thanks for helping my sort my problem here. I’m curious for what might have gone wrong with the write out of the intermediate files, but it’s not an urgent issue.

**Comment by martindurant** [comment]
```
In [24]: outs0["refs"]["var167/158.0.0"]
Out[24]: ['{{u}}', 4609580, 28800]

In [25]: outs0["templates"]
Out[25]: {'u': '/Users/mdurant/Downloads/kerchunk_file_formats_comparison/t2m_jan_00866.nc'}

In [26]: ll /Users/mdurant/Downloads/kerchunk_file_formats_comparison/t2m_jan_00866.nc
-rw-rw-r--@ 1 mdurant  staff  21525932 29 Apr 08:41 /Users/mdurant/Downloads/kerchunk_file_formats_comparison/t2m_jan_00866.nc
```
Seems like that offset and size are reasonable for the given file?

The biggest offset in the linked gist is 21497132, just below the size of the file.

**Comment by rbanick** [comment]
You are correct, I was misreading the `length` to be the total length, not the length of that chunk. 

I’m not sure what the issue is then. Something in this line?
`out_file.write(ujson.dumps(h5chunks.translate()).encode())`

**Comment by rbanick** [comment]
You solved my problem by giving me a working method to read the intermediate JSONs in memory. Thank you! I was just digging a bit deeper to understand why reading the intermediate JSONs from disk caused the file size explosion.

Anyways the primary issue is resolved here so I’ll close this now.
