### ISSUE TITLE
AttributeError: 'ReferenceFileSystem' object has no attribute 'fs'

### ISSUE THREAD

**Issue by b-pos465** [fsspec/kerchunk#158]
The following issues does not occur with current versions of **Kerchunk**. However, it took me a whole day to figure out what is going on, so maybe it's useful for others searching for the following error when trying to use `MultiZarrToZarr`:

```python
Traceback (most recent call last):
  File "/home/python/.local/lib/python3.8/site-packages/fsspec_reference_maker/combine.py", line 69, in translate
    ds, ds0, fss = self._determine_dims()
  File "/home/python/.local/lib/python3.8/site-packages/fsspec_reference_maker/combine.py", line 255, in _determine_dims
    self.fs = fss[0].fs
AttributeError: 'ReferenceFileSystem' object has no attribute 'fs'
```

This issue occurs when an old version of [kerchunk](https://pypi.org/project/kerchunk/#history) is used. Before release of version `0.0.5` the library was called **fsspec-reference-maker**. As I followed the blog post [Reading GOES NetCDF4 data on AWS S3 as Zarr for rapid data access](https://medium.com/pangeo/fake-it-until-you-make-it-reading-goes-netcdf4-data-on-aws-s3-as-zarr-for-rapid-data-access-61e33f8fe685) I installed the old module via pip: 

```shell
python -m pip install fsspec-reference-maker
```

Unfortunately, version `0.0.4` does not work with recent versions of `fsspec` and produces the error above.

I fixed the issue by installing ` kerchunk` instead of `fsspec-reference-maker`:

```shell
python -m pip install kerchunk
```

# Suggestion

It would be helpful to release the package `kerchunk` under both names `kerchunk` and `fsspec-reference-maker`. This would make sure that online examples are still valid. Alternatively or in addition, a hint in the `README.md` would make it easier to understand what is going on. I had to search the issues, the commits, the tags and the pip registry to find this information.

**Comment by lsterzinger** [comment]
Hi @b-pos465,

This is a good point. I wrote that blog post in Kerchunk's infancy and the change of name isn't well documented anywhere. Since that post is still getting a decent amount of attention, I will make a note to update it with the new name/repo and some of the API calls that have changed.

**Comment by b-pos465** [comment]
@lsterzinger Perfect, thank you!

**Comment by lsterzinger** [comment]
Hi all - sorry for the delay, but I refreshed/updated the Medium blog post to reflect some of the changes in Kerchunk since it was written. https://medium.com/pangeo/fake-it-until-you-make-it-reading-goes-netcdf4-data-on-aws-s3-as-zarr-for-rapid-data-access-61e33f8fe685

**Comment by martindurant** [comment]
Hurray!
So we can close this?

**Comment by lsterzinger** [comment]
I think so, making sure the symlinking of fsspec-reference-maker to kerchunk seems unnecessary now that most of the pre-name-change documentation/guides have been updated

**Comment by martindurant** [comment]
I somehow STILL haven't made a releast of fsspec-reference-makewr that just instals kerchunk instead.
