### ISSUE TITLE
Concat CMIP ensemble members

### ISSUE THREAD

**Issue by Yefee** [fsspec/kerchunk#165]
Dear all,

I have a bunch of jsons encoding CMIP6 ensemble members. I am going to combine these jsons using MultiZarrToZarr. 
Below is an example of CanESM5. 
`'./jsons/ts_Amon_CanESM5_historical_r19i1p1f1_gn_185001-201412.nc.json',
 './jsons/ts_Amon_CanESM5_historical_r19i1p2f1_gn_185001-201412.nc.json',
 './jsons/ts_Amon_CanESM5_historical_r8i1p2f1_gn_185001-201412.nc.json',
 './jsons/ts_Amon_CanESM5_historical_r17i1p2f1_gn_185001-201412.nc.json',
 './jsons/ts_Amon_CanESM5_historical_r11i1p2f1_gn_185001-201412.nc.json',
 './jsons/ts_Amon_CanESM5_historical_r5i1p1f1_gn_185001-201412.nc.json',
...`

Each json encodes an ensemble member _r##i#p#f#_, which has dims (time, lat, lon). The member info is marked as **variant_label** in the zarr attributes:
`.zattrs: "{ "CCCma_model_hash": "7e8e715f3f2ce47e1bab830db971c362ca329419", ......, "tracking_id": "hdl:21.14100/d1ffa59d-8d7b-4cef-9a9a-7c75cdacebe1", "variable_id": "ts", "variant_label": "r19i1p1f1", "version": "v20190429" }"`

Specifying concat_dims=["variant_label"] fails this task.

```
fnames = glob('./jsons/*CanESM5*.json')
json_files = ['file://' + os.path.abspath(fname) for fname in fnames]
mzz = MultiZarrToZarr(
    json_files,
    concat_dims=["variant_label"],
    identical_dims=['lat','lon','time'],
    remote_protocol='file'
)
out = mzz.translate(None)
with open('ts_CanESM5_historical_combined.json', 'wt') as fp:
    json.dump(out, fp)
```
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/6420873/169659443-1f2bdf02-50d3-4618-858c-3630adf00483.png">

I could use xr.open_mfdataset to open these jsons by assigning a coord to each member.

```
def add_coord(ds):
    ds.coords['member'] = ds.attrs['variant_label']
    return ds

#fname is a list of json files.

m_list = []
for js in tqdm(fnames):
    with open(js) as f:
        m_list.append(fsspec.get_mapper("reference://", 
            fo=json.load(f), remote_protocol="file",
            remote_options={"anon": True}))
        
ds = xr.open_mfdataset(m_list, combine='nested', decode_times=False,
                       engine='zarr', coords='minimal',concat_dim='member',
                       data_vars='minimal', compat='override',preprocess=add_coord)
```

<img width="590" alt="image" src="https://user-images.githubusercontent.com/6420873/169659402-edbdaeec-3c9a-4714-b4c1-d0044ebe7de9.png">

I am wondering if there is a similar argument that let MultiZarrToZarr use attribution to concat files?

**Comment by keewis** [comment]
have a look at the `coo_map` parameter for this. In particular, `coo_map={"member": "attr:variant_label"}` might do what you're looking for.

**Comment by Yefee** [comment]
It worked! Thanks!
