### ISSUE TITLE
Invalid distance too far back

### ISSUE THREAD

**Issue by Yefee** [fsspec/kerchunk#168]
Somehow I find opening a list of single json and doing calculation is much slower and even return error  related to zlib

jsons0 includes ts and ua combined along ensemble member and time axis from EC-Earth historical simulation in CMIP6. I subset the dataset and load it into the memory, but it returns a weird error related to zlib.
```
jsons0 = ['./GDrive/historical/CMIP6/EC-Earth3/ts_CMIP6_EC-Earth3_combined_historocal.json', 
 './GDrive/historical/CMIP6/EC-Earth3/ua_CMIP6_EC-Earth3_combined_historocal.json']

m_list = []
for js in tqdm(jsons0):
    with open(js) as f:
        m_list.append(fsspec.get_mapper("reference://", 
            fo=json.load(f), remote_protocol="file",
            remote_options={"anon": True}))

ds = xr.open_mfdataset(m_list, combine='nested',
           engine='zarr', coords='minimal',
           data_vars='minimal', compat='override', consolidated=False,                   
           drop_variables=['i', 'j', 'latitude', 'lat_bnds','lon_bnds','plev_bnds',
                           'longitude', 'vertices_latitude','time_bounds',
                          'vertices_longitude'], chunks={'time':120})

ds = ds.sel(plev=[20000., 85000.], lat=slice(0, 60), lon=slice(240, 360))
ds = ds.compute()
```
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/6420873/170901792-bdd8cd6b-bf6a-4071-af82-1e44ff42c3f1.png">
...
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/6420873/170901569-9559111d-24d9-48ae-8a31-a000e42e2bef.png">

However, when I use MultiZarrToZarr to combine the jsons and open the data the same way, it works great and much faster! 
json1 is the combined ua and ts.
```
jsons1 = ['./GDrive/historical/CMIP6/EC-Earth3/ts.EC-Earth3_historical_combined.json']
fs = fsspec.filesystem(
    "reference", 
    fo=jsons1[0], 
    remote_protocol="file", 
    remote_options={"anon":True},
    skip_instance_cache=True)
m = fs.get_mapper("")

ds = xr.open_dataset(m, engine='zarr', decode_times=False,consolidated=False, 
                     drop_variables=['i', 'j', 'latitude', 'lat_bnds','lon_bnds','plev_bnds',
                                                       'longitude', 'vertices_latitude','time_bounds',
                                                      'vertices_longitude'], chunks={'time':120})
ds = ds.sel(plev=[20000., 85000.], lat=slice(0, 60), lon=slice(240, 360))
ds = ds.compute()
ds
```
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/6420873/170901815-e772eb0d-5641-4f9b-aea4-155dcb8816b2.png">

**Comment by martindurant** [comment]
Is the message here, that kerchunk does a better job of combining data sets (hurray!), or that something is wrong with the intermediate reference sets, and openmfdataset ought to be able to cope?

**Comment by Yefee** [comment]
solved. due to inconsistent lat among variables.
