### ISSUE TITLE
NameError: name 'ujson' is not defined

### ISSUE THREAD

**Issue by najiya-12** [fsspec/kerchunk#170]
I listed the files from S3 
`urls = ['s3://' + f for f in fs.glob("s3://noaa-goes16/ABI-L2-ACMC/2022/116/*/*.nc")]`
given around 
`len(urls)`
272 files 
and then generated the `jsons` files and created in the `./jsons/` directory, however, I run into an issue with `gen_json()` function 
`NameError: name 'ujson' is not defined`. I followed  @lsterzinger tutorial in  [https://medium.com/pangeo/fake-it-until-you-make-it-reading-goes-netcdf4-data-on-aws-s3-as-zarr-for-rapid-data-access-61e33f8fe685](url)

**Comment by peterm790** [comment]
Try installing and importing the ujson package: https://pypi.org/project/ujson/ . I believe it is functionally the same as the normal json encoder just a bit faster

**Comment by najiya-12** [comment]
> Thanks for catching this typo @najiya-12 - I corrected the import to `import ujson` at the beginning of the tutorial. As @martindurant said, it should be installed alongside Kerchunk since it's listed in the dependencies

It worked

**Comment by keewis** [comment]
there's still a typo:
```python
m_list = []
for js in tqdm(json_list):
    with open(js) as f:
        m_list.append(fsspec.get_mapper("reference://", 
            fo=json.load(f), remote_protocol="s3",
            remote_options={"anon": True}))
```
`json` → `ujson`
