### ISSUE TITLE
accessing three months of data using fsspec 

### ISSUE THREAD

**Issue by najiya-12** [fsspec/kerchunk#171]
The way `noaa-goes16/ABI-L2` data is stored in s3 has limited access for  one day of data for (# of files around 288)  using this command: 

`fs = fsspec.filesystem('s3', anon=True)`

`urls = ['s3://' + f for f in fs.glob("s3://noaa-goes16/ABI-L2-ACMC/2022/001/*/*.nc")]`

or one hour ((# of files around 12) 
``urls = ['s3://' + f for f in fs.glob("s3://noaa-goes16/ABI-L2-ACMC/2022/001/04/*.nc")]``

Is there any way to work around this to have access to around  three months of data(100 consecutive days)

**Comment by najiya-12** [comment]
you are here, `fs.glob("s3://noaa-goes16/ABI-L2-ACMC/2022/**/*.nc")`, considering around 44505 files! costing 2.269 GB of  the sysyem's memoery   
You side "You would not normally rebuild for each specific view you need, although you can", How can we do handle that

**Comment by lsterzinger** [comment]
If you're just interested in 3 months of data, you can use the code in the blog post to generate a daily JSON (100 JSON files total). Then, using a similar approach to combining the 24 hourly JSONs into a daily JSON, you can use `MultiZarrToZarr` to combine the 100 daily JSONs into a single file representing all 100 days.

**Comment by martindurant** [comment]
44.5k files is not so many from our point of view. Neither is 2.3GB of system memory, although I'm not sure what this refers to. Yes, as @lsterzinger says, you can be specific, but kerchunk as a project will tend to want to make reference sets as complete/general as possible.

**Comment by najiya-12** [comment]
@martindurant the number of  (44.5k files) refers to the data recorded in 2022 on 5 minutes resolution from goes16 up to yesterday. Each JSON file carried 51KB(in total 2.3GB). my aim is to apply some processing and computation for an ML algorithm using this data. Defenility I can benefit from kerchunk in terms of reducing the size of the files downloaded. However, it took too long to download 5 days of data(1440 files). 

@lsterzinger, I reused your code by accessing the number of days I need as follows:  

`urls1=[]
for i in range (5):
    urls = ['s3://' + f for f in fs.glob("s3://noaa-goes16/ABI-L2-CODC/2022/001/*/*.nc")]
    urls1 = urls1+ urls`

however, when i got running gen_json() function with Dask, it kept runing without any results 
`dask.compute(*[dask.delayed(gen_json)(u) for u in urls])`

**Comment by najiya-12** [comment]
Sure, have you received it!

**Comment by lsterzinger** [comment]
Check the last few files in the list, in your original code it is just the 1st day of data (2022/001/*) that is being repeated 5 times whereas with the new loop it should get all days from 2022/001 - 2022/004 (since in the first iteration i=0, which does not return any files since there is no 0th day).


Lucas Sterzinger (he/him)
PhD Candidate
UC Davis Cloud Physics Research Group
Hoagland Hall 236
***@***.***
https://lucassterzinger.com

**Comment by lsterzinger** [comment]
Yes, that's what I mentioned in my previous comment (though I could have worded it better). This stores the JSON contents as dictionaries in memory, and that list (say `ref_list` where `ref_list = dask.compute(*[dask.delayed(gen_json)(u) for u in urls1])`) can be passed directly to `MultiZarrToZarr` to make a combined reference for all the files, without having to save the individual JSONs to disk. This may or may not be preferred for your workflow.

**Comment by najiya-12** [comment]
So I have either, no JSON files or None returned by the function

**Comment by lsterzinger** [comment]
> So I have either, no JSON files or None returned by the function

Correct. If you write JSON, the function will return None. This is expected and normal. If you want the function to return the metadata info without writing to JSON, use the `gen_json` function I provided above.

**Comment by martindurant** [comment]
> @martindurant the number of (44.5k files) refers to the data recorded in 2022 on 5 minutes resolution from goes16 up to yesterday. Each JSON file carried 51KB(in total 2.3GB).

This arithmetic is incorrect: because there is a lot of duplication between the individual files, you expect the composite dataset reference file to be much smaller. Alse, we have found that Zstd does a very good job of compressing these.

**Comment by najiya-12** [comment]
> ```python
> def gen_json(u):
>     so = dict(
>         mode="rb", anon=True, default_fill_cache=False,
>         default_cache_type="none")
>     with fsspec.open(u, **so) as inf:
>         return SingleHdf5ToZarr(inf, u, inline_threshold=300).translate()
> ```

**Comment by najiya-12** [comment]
> > So I have either, no JSON files or None returned by the function
> 
> Correct. If you write JSON, the function will return None. This is expected and normal. If you want the function to return the metadata info without writing to JSON, use the `gen_json` function I provided above.

I proceed by creating JSON files and the function returned  `None `, but the produced files contained metadata and I was able to extract the needed data! So what the` None ` refers to!!

**Comment by najiya-12** [comment]
@lsterzinger  Beautiful! thank you a lot!  that is why your blog's title refers to "**_fake-it-until-you-make-it"_**

**Comment by lsterzinger** [comment]
Happy to help!
