### ISSUE TITLE
"TypeError: reject_bytes is on.." when utilising postproces in MultiZarrtoZarr

### ISSUE THREAD

**Issue by peterm790** [fsspec/kerchunk#176]
Postprocess in [MultiZarrtoZarr](https://github.com/fsspec/kerchunk/blob/main/kerchunk/combine.py) is a useful way to modify attributes such as that suggested in https://github.com/fsspec/kerchunk/issues/173 

However at present the following will work to create a combined json file but will not work when writing to json: 

      import zarr 
      def modify_fill_value(out):
          out_zarr = zarr.open(out)
          out_zarr.y.fill_value = 10
          return out
      
      def postprocess(out):
          out = modify_fill_value(out)
          return out

instead the following is necessary:

      import base64
      
      def consolidate(out):
          for k, v in out.items():
              if isinstance(v, bytes):
                  try:
                      # easiest way to test if data is ascii
                      out[k] = v.decode('ascii')
                  except UnicodeDecodeError:
                      out[k] = (b"base64:" + base64.b64encode(v)).decode()
              else:
                  out[k] = v
          return out
      
      import zarr
      
      def modify_fill_value(out):
          out_zarr = zarr.open(out)
          out_zarr.y.fill_value = 10
          return out
      
      def postprocess(out):
          out = modify_fill_value(out)
          out = consolidate(out)
          return out 

a reproducible notebook using post-process is available here https://gist.github.com/peterm790/4b1632cfea9f76cd75f07b22364258b8 

@martindurant suggested this could be solved by changing `consolidate` to a function rather than a module in https://github.com/fsspec/GSoC-kechunk-2022/issues/5 another option is to move postprocess to the beginning of the consolidate module. 

https://github.com/fsspec/kerchunk/blob/10908098cc5a179c580ae92bf0bd1c5d3165ffa8/kerchunk/combine.py#L382-L397

**Comment by martindurant** [comment]
> could be solved by changing consolidate to a function rather than a module in https://github.com/fsspec/GSoC-kechunk-2022/issues/5 another option is to move postprocess to the beginning

These two are not mutually exclusive :)
