### ISSUE TITLE
FillValue issues with kerchunk 1e37=> 9.99999993e+36

### ISSUE THREAD

**Issue by rsignell-usgs** [fsspec/kerchunk#177]
In my original NetCDF4 file (HDF5 under the hood) the fill value `_FillValue` is set to `1.e+37` for 32bit floats, and when loaded into xarray with `decode_cf=True`, the data values with 1e37 are correctly interpreted as fill values and set to NaN. 

In the kerchunk JSON, the `_FillValue` in the JSON is set to 9.99999993e+36 and when loaded into xarray with `decode_cf=True`, the data values are not interpreted as fill values, and show up as 9.99999993e+36 (not 1e37 and not NaN). 

Pretty confused on what is going on here!

Here is a [Reproducible Notebook](https://nbviewer.org/gist/d66b81e9322b1216e496930a555f3cb2)

cc @peterm790

**Comment by martindurant** [comment]
My hunch was, that this is due to writing the value as text in the attributes of zarr. But that raises the question of how this is normally handled outside of kerchunk, and why decode_cf matters.

**Comment by martindurant** [comment]
@rsignell-usgs , do you mind using xarray's to_zarr on that dataset to see what .zarray/.zattrs it creates? You can set the output chunk store (as opposed to the metadata store) to be a dict or even a custom dict that doesn't store anything (see below) to avoid writing things.


```python
class NoOpDict(dict):
    def __setitem__(self, *_):
        pass

metadata_strore = {}
chunk_store = NoOpDict()
```

**Comment by keewis** [comment]
> That must be an HDF5-specific thing?

yes, exactly. You can examine it with
```python
In [1]: import fsspec
   ...: import h5py
   ...: 
   ...: fs = fsspec.filesystem(
   ...:     "s3", anon=True, client_kwargs={"endpoint_url": "https://mghp.osn.xsede.org"}
   ...: )
   ...: url = "s3://rsignellbucket1/COAWST/coawst_us_20220101_01.nc"
   ...: 
   ...: f = h5py.File(fs.open(url))
   ...: f["temp"].fillvalue
Out[1]: 0.0
```

For [`float` values](https://github.com/fsspec/kerchunk/blob/10908098cc5a179c580ae92bf0bd1c5d3165ffa8/kerchunk/hdf.py#L196) it is used to set `zarr`'s [`fill_value`](https://github.com/fsspec/kerchunk/blob/10908098cc5a179c580ae92bf0bd1c5d3165ffa8/kerchunk/hdf.py#L214) attribute, which AFAIU the `zarr` engine will use to *replace* `_FillValue`.

You might have to synchronise `fill_value` with `_FillValue` in the references (e.g. by passing the hacky function from https://github.com/fsspec/kerchunk/issues/105#issuecomment-982834456 to `MultiZarrToZarr`'s `preprocess`). For example:

<details><summary>ipython session</summary>

```python
In [1]: import fsspec
   ...: 
   ...: fs = fsspec.filesystem(
   ...:     "s3", anon=True, client_kwargs={"endpoint_url": "https://mghp.osn.xsede.org"}
   ...: )
   ...: url = "s3://rsignellbucket1/COAWST/coawst_us_20220101_01.nc"
   ...: 
   ...: import kerchunk.hdf
   ...: 
   ...: hdf = kerchunk.hdf.SingleHdf5ToZarr(fs.open(url), url=url)
   ...: references = hdf.translate()
       
In [2]: import xarray as xr
   ...: 
   ...: r_opts = dict(anon=True, client_kwargs={"endpoint_url": "https://mghp.osn.xsede.org"})

In [3]: fs = fsspec.filesystem(
   ...:     "reference", fo=references, remote_protocol="s3", remote_options=r_opts
   ...: )
   ...: m = fs.get_mapper("")
   ...: 
   ...: ds = xr.open_dataset(
   ...:     m,
   ...:     engine="zarr",
   ...:     chunks={},
   ...:     backend_kwargs=dict(consolidated=False),
   ...:     decode_cf=False,
   ...: )

In [4]: ds.temp.attrs
Out[4]: 
{'_FillValue': 0.0,
 'coordinates': 'lon_rho lat_rho s_rho ocean_time',
 'field': 'temperature, scalar, series',
 'grid': 'grid',
 'location': 'face',
 'long_name': 'potential temperature',
 'time': 'ocean_time',
 'units': 'Celsius'}

In [5]: ds.temp[0, 0, 0, 0].values
Out[5]: array(1.e+37, dtype=float32)

In [6]: decoded = xr.decode_cf(ds)
   ...: decoded.temp[0, 0, 0, 0].values
Out[6]: array(1.e+37, dtype=float32)

In [7]: import ujson
   ...: import itertools
   ...: 
   ...: 
   ...: def correct_fill_values(data):
   ...:     def fix_variable(values):
   ...:         zattrs = values[".zattrs"]
   ...: 
   ...:         if "_FillValue" not in zattrs:
   ...:             return values
   ...: 
   ...:         _FillValue = zattrs["_FillValue"]
   ...:         if values[".zarray"]["fill_value"] != _FillValue:
   ...:             values[".zarray"]["fill_value"] = _FillValue
   ...: 
   ...:         return values
   ...: 
   ...:     refs = data["refs"]
   ...:     prepared = (
   ...:         (tuple(key.split("/")), value) for key, value in refs.items() if "/" in key
   ...:     )
   ...:     filtered = (
   ...:         (key, ujson.loads(value))
   ...:         for key, value in prepared
   ...:         if key[1] in (".zattrs", ".zarray")
   ...:     )
   ...:     key = lambda i: i[0][0]
   ...:     grouped = (
   ...:         (name, {n[1]: v for n, v in group})
   ...:         for name, group in itertools.groupby(sorted(filtered, key=key), key=key)
   ...:     )
   ...:     fixed = ((name, fix_variable(var)) for name, var in grouped)
   ...:     flattened = {
   ...:         f"{name}/{item}": ujson.dumps(data, indent=4)
   ...:         for name, var in fixed
   ...:         for item, data in var.items()
   ...:     }
   ...:     data["refs"] = dict(sorted((refs | flattened).items()))
   ...:     return data

In [8]: corrected_refs = correct_fill_values(references)

In [9]: fs = fsspec.filesystem(
   ...:     "reference", fo=corrected_refs, remote_protocol="s3", remote_options=r_opts
   ...: )
   ...: m = fs.get_mapper("")
   ...: 
   ...: ds = xr.open_dataset(
   ...:     m,
   ...:     engine="zarr",
   ...:     chunks={},
   ...:     backend_kwargs=dict(consolidated=False),
   ...:     decode_cf=False,
   ...: )
   ...: display(ds.temp.attrs, ds.temp[0, 0, 0, 0].values)
{'_FillValue': 1e+37,
 'coordinates': 'lon_rho lat_rho s_rho ocean_time',
 'field': 'temperature, scalar, series',
 'grid': 'grid',
 'location': 'face',
 'long_name': 'potential temperature',
 'time': 'ocean_time',
 'units': 'Celsius'}
array(1.e+37, dtype=float32)

In [10]: decoded = xr.decode_cf(ds)
    ...: decoded.temp[0, 0, 0, 0].values
Out[10]: array(nan, dtype=float32)
```

</details>

**Comment by keewis** [comment]
> The `fill_value` is set to 9.999999e+36, but when read back into xarray with `cf_decode=False`, the value is 1e37

That might be a precision / formatting issue:
```python
In [33]: np.float32(9.999999933815813e36)
Out[33]: 1e+37

In [34]: np.float64(9.999999933815813e36)
Out[34]: 9.999999933815813e+36
```

**Comment by martindurant** [comment]
@keewis , you mean the `correct_fill_values` function?

**Comment by keewis** [comment]
yes

**Comment by rabernat** [comment]
Ok something even more obvious.

```python
dsk = xr.open_dataset(m, engine="zarr", chunks={}, 
                     backend_kwargs=dict(consolidated=False), decode_cf=False)
dsk.temp._FillValue  # -> 0.0
```

**So the zarr array fill_value is actually overwriting the fill value already in the attributes by Xarray!** Manually overriding does the trick

```python
dsk.temp.attrs['_FillValue'] = kerchunk_attrs_fill_value
xr.decode_cf(dsk).temp[0, 0, 0, 0].values  # -> NaN
```

This may be an xarray bug. The problem is ultimately the duplicate and inconsistent fill_values.

**Comment by rabernat** [comment]
This is the specific place where the overwriting happens: https://github.com/pydata/xarray/blob/d7931f9014a26e712ff5f30c4082cf0261f045d3/xarray/backends/zarr.py#L455-L456

So there are two simultaneous paths forward:
- Consider this an xarray bug, and make a PR to xarray to do something when it discovers two inconsistent fill values attributes. The most likely action would be to raise an error or warning.
- Regardless of that, kerchunk should strive to not produce inconsistent data (different values of array `.fill_value` and attribute `_FillValue`.

**Comment by rsignell-usgs** [comment]
@rabernat you are awesome!  Thanks for showing us the path!

**Comment by rsignell-usgs** [comment]
@keewis , you said the original NetCDF4 file had `fill_value` set, but I did: 
```
 h5dump -H coawst_us_20220101_13.nc > h5dump.txt
```
and searching the resulting file for "fill_value" comes up empty.  

The `temp` variable looks like this:
```
   DATASET "temp" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 12, 16, 336, 896 ) / ( H5S_UNLIMITED, 16, 336, 896 ) }
      ATTRIBUTE "DIMENSION_LIST" {
         DATATYPE  H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }}
         DATASPACE  SIMPLE { ( 4 ) / ( 4 ) }
      }
      ATTRIBUTE "_FillValue" {
         DATATYPE  H5T_IEEE_F32LE
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      }
      ATTRIBUTE "coordinates" {
         DATATYPE  H5T_STRING {
            STRSIZE 32;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "field" {
         DATATYPE  H5T_STRING {
            STRSIZE 27;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "grid" {
         DATATYPE  H5T_STRING {
            STRSIZE 4;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "location" {
         DATATYPE  H5T_STRING {
            STRSIZE 4;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "long_name" {
         DATATYPE  H5T_STRING {
            STRSIZE 21;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "time" {
         DATATYPE  H5T_STRING {
            STRSIZE 10;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "units" {
         DATATYPE  H5T_STRING {
            STRSIZE 7;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
   }
```
You saw the `fill_value` attribute when you read the dataset with h5py, right?

**Comment by keewis** [comment]
yes, exactly. I'm not sure where that gets the value, though.

**Comment by rsignell-usgs** [comment]
So sounds like h5py also handles the fill values inconsistently!

**Comment by ajelenak** [comment]
Fill value is a property of an HDF5 dataset (same as a netCDF variable or Zarr array) which is assigned at its creation. If it is not set explicitly, the HDF5 library assigns the default value which for all numerical datatypes is zero, I think. That should be shown with `h5dump -p ...` command. This is **not** an HDF5 attribute. H5py just uses what the library says is the fill value of that dataset.

`_FillValue` is a netCDF attribute (same as HDF5/Zarr attribute) and has no relation to the HDF5 dataset fill value. So you can, and often do, end up with these two values being different in netCDF-4 files. AFAIK, the netCDF library does not sync up these two values, likely because an attribute's value can be modified later but the HDF dataset fill value is immutable.

That part of the kerchunk code is still the original I wrote and it does the right thing in my opinion: translates HDF5 dataset fill value to Zarr array fill value.

How to interpret the Zarr array fill value vs `_FillValue` Zarr atribute is up to the upstream software, like xarray, to decide. And also deal with numerical rounding errors of tricky fill values.

**Comment by rsignell-usgs** [comment]
@ajelenak thanks for this explanation!   

So if `xarray` sets the `_FillValue` attribute when writing Zarr, and reads the `_FillValue` attribute when reading Zarr, we should be fine, right?

**Comment by ajelenak** [comment]
```python
with xarray.netcdf_and_cf_context as ds:
    answer = yes
```

**Comment by rabernat** [comment]
> So if `xarray` sets the `_FillValue` attribute when writing Zarr, and reads the `_FillValue` attribute when reading Zarr, we should be fine, right?

This is explicitly how we coded it when we implemented the zarr backed. The array internal `fill_value` property (analogous to the HDF5 fill_value) is lifted in the `_FillValue` attribute when decoding from Zarr. And the reverse happens at write time.

I think the problem is that Kerchunk does not use the same code path as Xarray when creating a new Zarr store, so it does not have this logic of setting `.fill_value` on the Zarr array itself based on the `_FillValue` attribute. So the default `.fill_value==0` is being used. My recommendation is to try to align the Kerchunk Zarr writer more closely with Xarray and, if possible, leverage Xarray's encoding / decoding.

Another problem is that Xarray just overwrites any existing `_FillValue` attribute without checking if it  already exists ([code here](https://github.com/pydata/xarray/blob/d7931f9014a26e712ff5f30c4082cf0261f045d3/xarray/backends/zarr.py#L455-L456)). Raising a warning or error would be better. That would have helped track down this bug more easily.

**Comment by martindurant** [comment]
OK, so kerchunk is happy to fill in the `_FillValue` attribute. I anticipate that in any tool that is not xarray, or with cf decoding off, this will simply be ignored. I'll make that change, we can rerun the fail case and see if all is good. Next week... :)

**Comment by rsignell-usgs** [comment]
@martindurant , I believe what we want is to make the Kerchunk  .zarray `fill_value` match the `_FillValue` attribute for each variable.

**Comment by martindurant** [comment]
Can anyone suggest a simple test case for #181 ?

**Comment by kthyng** [comment]
This may or may not be directly related to this issue but it was what I found when I googled my problem so I'll add a comment here.

I found that if a scalar value being kerchunked from a file is 0.0 and the fill value is 0.0, it comes into the dataset as nan. As in:
```
out["hc/.zarray"]
```
returns
```
'{"chunks":[],"compressor":null,"dtype":"<f8","fill_value":0.0,"filters":null,"order":"C","shape":[],"zarr_format":2}'
```
and also I know from the original model output that the value of `hc` is 0.0. It has to be exactly this combination from what I can tell — other scalar values with fill_value of 0.0 weren't changed when examined in the resulting dataset. I was able to fix this by postprocessing my kerchunking while running `MultiZarrToZarr` like so:
```
fs2 = fsspec.filesystem('')  # local file system to save final jsons to

fname_overall_kerchunk = "kerchunk.json"
json_list = fs2.glob(f"{output_dir_single_files}/1999_000?.json") # combine single json files


def fix_fill_values(out):
    """Fix problem when fill_value and scara both equal 0.0.
    
    If the fill value and the scalar value are both 0, nan is filled instead. This fixes that.
    """

    for k in list(out):
        if isinstance(out[k], str) and '"fill_value":0.0' in out[k]:
            out[k] = out[k].replace('"fill_value":0.0', '"fill_value":"NaN"')
    return out

def postprocess(out):
    out = fix_fill_values(out)
    return out

mzz = MultiZarrToZarr(
    json_list,
    concat_dims=["ocean_time"],
    identical_dims= ['lat_rho', 'lon_rho', "lon_psi", "lat_psi",
                    "lat_u", "lon_u", "lat_v", "lon_v", 
                    "Akk_bak","Akp_bak","Akt_bak","Akv_bak","Cs_r","Cs_w",
                    "FSobc_in","FSobc_out","Falpha","Fbeta","Fgamma","Lm2CLM",
                    "Lm3CLM", "LnudgeM2CLM", "LnudgeM3CLM", "LnudgeTCLM",
                    "LsshCLM", "LtracerCLM", "LtracerSrc", "LuvSrc",
                    "LwSrc", "M2nudg", "M2obc_in", "M2obc_out", "M3nudg",
                    "M3obc_in", "M3obc_out", "Tcline", "Tnudg","Tobc_in", "Tobc_out",
                    "Vstretching", "Vtransform", "Znudg", "Zob", "Zos", "angle",
                    "dstart", "dt", "dtfast", "el", "f", "gamma2", "grid", "h",
                    "hc", "mask_psi", "mask_rho", "mask_u", "mask_v", "nHIS", "nRST",
                    "nSTA", "ndefHIS",  "ndtfast", "ntimes", "pm", "pn", "rdrg", 
                    "rdrg2", "rho0", "spherical", "theta_b", "theta_s", "xl",
                    ],
    coo_map = {"ocean_time": "cf:ocean_time",
               },
    postprocess=postprocess,
)
```

This could also be fixed in preprocessing but it seemed like it would be faster to do postprocessing one time per variable.

cc @martindurant this is the issue I mentioned earlier today.

**Comment by martindurant** [comment]
That pre/post processing function could be included a an example in kerchunk itself alongside the current `drop()` one. I'm not sure if there's a way we should be doing this at the scan stage given the discussion above about fill_value and _FillValue. A legitimate "0 means NaN" seems unlikely even for ints, where I would expect maybe -1, 9999, max_int for this purpose. 

This was netCDF/HDF data? I wonder if there's a flag to say "no missing values" for a whole array.

**Comment by kthyng** [comment]
netCDF yes.

**Comment by martindurant** [comment]
You could put a breakpoint() in SinhleHdf5ToZarr._translator() to see if there's anything about the particular `h5obj` that says it has absolutely no missing values
(cc @ajelenak )

**Comment by ajelenak** [comment]
Yes, debugging can help. Alternatively, the output of this command: `h5dump -d /path/to/ncvar -p -A the_file.nc` should provide all the relevant storage information.
