### ISSUE TITLE
Problem creating combined JSON from single file JSONs on OSN endpoint_url

### ISSUE THREAD

**Issue by rsignell-usgs** [fsspec/kerchunk#178]
I'm trying out using an Open Storage Network (OSN) storage with s3 interface, but we need `endpoint_url`.   

I've successfully written the individual JSONs to the OSN bucket, but the MultiJSON step is having issues:

https://nbviewer.org/gist/rsignell-usgs/27c5a47e7bea42a8564b3041efbd3d91

**Comment by martindurant** [comment]
When constructing MultiZarrToZarr, remote_options refers to where the original files are, and target_options to where the input JSONs are - you need both, just like when making the filesystem in the cell above.
