### ISSUE TITLE
Speeding up MultiZarrToZarr

### ISSUE THREAD

**Issue by peterm790** [fsspec/kerchunk#182]
I have been creating kerchunk files for the [ERA5 public dataset ](https://registry.opendata.aws/ecmwf-era5/) on AWS. Which has worked well so far. 

However a botteneck is that it takes over 3 hours for `MultiZarrtoZarr` to run on a medium (2 CPU 8 GB RAM) amazon EC2 instance. This is understandable as each json before combining has 3720 chunks and there are 521 files to combine, a total of > 1.9 million chunks. The problem is the length taken to run  `MultiZarrtoZarr` often results in it timing out. 

I had hoped dividing it into smaller batches to run in parallel would solve this:

      len(json_list) # -> 521
      json_split = np.array_split(np.array(json_list),20) #<- create 20 smaller lists of individual json files
      json_split = [list(x) for x in json_split]
      len(json_split) # -> 20 (list of lists)
      
      def multi_multizarr(json_list):
          mzz = MultiZarrToZarr(json_list,                
              remote_protocol='s3',
              remote_options={'anon':True},
              concat_dims=['time0'], #this is the dimension along which the individual files will be merged
              postprocess = postprocess
          )
          return mzz.translate()
      
      import dask
      
      jsons = []
      for json in json_split:
          x = dask.delayed(multi_multizarr)(json)
          jsons.append(x)

      d = dask.delayed(multi_multizarr)(jsons)
      
      %%time
      from dask.distributed import performance_report
      with performance_report(filename="dask-report-whole.html"):
          d.compute()

However this doesn't seem to be of much help, as while combining the smaller subsets runs much faster, combining these 'interim' jsons into the final json is still very slow. (I haven't completed a run but certainly > 3 hours) Which is no faster than combining straight from the original jsons from `SingleHdf5ToZarr`. I initially thought this may be from slow data transfer between clusters, but writing the interim files to S3 and running `MultiZarrtoZarr.translate` from there is still very slow. 

I'm not sure where exactly the bottlenek is inside `MultiZarrtoZarr.translate`.  Any suggestions how identify this, like in https://github.com/fsspec/kerchunk/issues/37? And any other ideas on how this could be sped up?

**Comment by martindurant** [comment]
Can you point me to the intermediates on S3? This needs creds?
