### ISSUE TITLE
scale_factor and add_offset need to be numbers, not strings

### ISSUE THREAD

**Issue by rsignell-usgs** [fsspec/kerchunk#211]
I tried using multizarr2zarr on NetCDF3 files with `scale_factor` and `add_offset`, and it bombed out because they were encoded as strings instead of numbers in the JSON. 

Do you need more info @martindurant ?

**Comment by martindurant** [comment]
Did you see https://github.com/fsspec/kerchunk/pull/210 ?

**Comment by rsignell-usgs** [comment]
nope!  Closing...
