### ISSUE TITLE
local variable 'ch' referenced before assignment

### ISSUE THREAD

**Issue by rsignell-usgs** [fsspec/kerchunk#219]
@martindurant , I'm getting:
``` 
UnboundLocalError: local variable 'ch' referenced before assignment
``` 
when doing the step:
```
mzz.translate()
```
in [this notebook](https://nbviewer.org/gist/63aa8e337610273737c337b860d96eea).

This is trying to create a combined JSON for some PRISM NetCDF files.

**Comment by martindurant** [comment]
I don't seem to be able to access those data files directly, so it's hard for me to look

**Comment by rsignell-usgs** [comment]
They are `requester_pays`.   You could use the esip-qhub to access?

**Comment by martindurant** [comment]
Oh, then it should be fine. The default profile on qhub was giving permission denied.

**Comment by rsignell-usgs** [comment]
I'm not getting that error anymore.   I don't know what's different but I'll close this and open again if I can reproduce.
