### ISSUE TITLE
single-file datasets

### ISSUE THREAD

**Issue by martindurant** [fsspec/kerchunk#220]
Zarr, by design, produces many files as chunks of the data. Likewise, a single logical netCDF dataset might be composed of many individual files. Sometimes it is convenient/necessary to distribute everything as a single file, .tar or .zip.

Zarr was designed to work with .zip files. You can even combine with fsspec to work on remote .zip files (to write complete datasets or read-only, *not* update). However, these maintain a single open file object with state.

In the case that the archive file is not compressed (since the contents already are), the contained C buffers are simple chunks in the overall archive. References can be made without the intermediate tar/zip driver just by adding the member file's offset to the individual offsets. In this way, you can get concurrent reads to the whole contained dataset (or several datasets). All we need is a small utility tool to find and apply the offsets.

**Comment by martindurant** [comment]
@tinaok , yes, exactly.

For .zip, you could even put the produced references set in the same file. That won't work for tar, because it would live at the *end* of the file, and need scanning through the whole thing to read; so in this case, the .json would need to live elsewhere.

**Comment by forrestfwilliams** [comment]
@martindurant my co-workers and I have spent some time thinking about this problem, since the Sentinel-1 datasets we distribute are in zip files. Using `fsspec` it's possible to remote read an entire dataset from a zip file using:
```python
    url = 'YOUR_ZIP_URL'
    auth = 'YOUR_AUTHORIZATION'
    path = 'PATH/TO/FILE.txt'

    storage_options = {'client_kwargs': {'trust_env': True, 'auth': auth}}
    http_fs = fsspec.filesystem('https', **storage_options)
    with http_fs.open(url) as http_f:
        zip_fs = fsspec.filesystem('zip', fo=http_f)
        with zip_fs.open(path) as f:
            file_bytes = f.read()
```

While this works, it runs into some issues that affect performance. In particular, `fsspec` tends to request the data in small chunks, which means that we are paying the authorization more often than is ideal. This issue appears to get worse if you request only a portion of a file by using an `f.seek()` call before the `f.read()` call.

**Comment by martindurant** [comment]
If you put some data in a public place (or send it to me), I can have a go at a utility to index within a .zip . Am I right in assuming that the members of the archive are uncompressed hdf files?

**Comment by forrestfwilliams** [comment]
I've just uploaded an example zipped dataset to a S3 bucket [here](https://hyp3-examples.s3.us-west-2.amazonaws.com/community/fsspec/S1A_IW_SLC__1SDV_20220830T070738_20220830T070806_044778_0558E1_F7D1.zip). Unfortunately, most of our use cases involve georiffs inside zipped archives, so this is what this archive contains. Here is some more specific example code that was attempting download bytes that correspond to a portion of a larger geotiff file:

```python
import fsspec

url = 'https://hyp3-examples.s3.us-west-2.amazonaws.com/community/fsspec/S1A_IW_SLC__1SDV_20220830T070738_20220830T070806_044778_0558E1_F7D1.zip'
path = 'S1A_IW_SLC__1SDV_20220830T070738_20220830T070806_044778_0558E1_F7D1.SAFE/measurement/s1a-iw1-slc-vv-20220830t070738-20220830t070806-044778-0558e1-004.tiff'
read_start = 119_915
read_length = 126_309_560

storage_options = {'client_kwargs': {'trust_env': True}}
http_fs = fsspec.filesystem('https', **storage_options)
with http_fs.open(url) as http_f:
    zip_fs = fsspec.filesystem('zip', fo=http_f)
    with zip_fs.open(path) as f:
        f.seek(read_start)
        file_bytes = f.read(read_length)
```

**Comment by martindurant** [comment]
I see that tile TIFF file in question is compressed within the ZIP. This means that it will not be possible to view chunks of is as simply byte ranges of the ZIP file (you can never seek within a gzip/deflate stream). The compression ratio is only 0.63, so it might have been OK to archive without compression. TIFF already has internal compression, and compressing compressed data is rarely very fruitful. Of course, if it wasn't up to you...

In any case, the trick we are won't work here. All I can suggest, is to increase the buffering, which will cut down the number of requests:
```
http_fs.open(url, block_size=100*2**20)
```

**Comment by martindurant** [comment]
```
read_length = 126_309_560
```
oh, this is almost the whole file. So I suppose you could HTTP-get the range corresponding to the whole compressed file and DEFLATE it by hand into the TIFF before selecting the buffer in question. But now we're a little outside of kerchunk, I think.

**Comment by martindurant** [comment]
@rabernat : not sure you've been following this, but I thought you might find it an interesting application of kerchunk.

**Comment by rsignell-usgs** [comment]
Just to make sure I understand:  we could store a zarr dataset in a zipfile, but we are just treating it as a file containing metadata and chunks of compressed binary data.   So we still want to use kerchunk to improve cloud performance, avoid using the zip library stuff, read the metadata all in one shot, then access the chunks concurrently via byte-range requests.

And we don't have this ability yet, but it would be just another format to handle. 

Did I get this right?

**Comment by martindurant** [comment]
Yes, all of that is correct. With addition: the contained files could actually be HDF or anything with internal buffers if the ZIP is uncompressed. This *already works*, except that we don't yet have the  utility to construct the required JSON references automatically (I did make a start). It could be done by hand, though.

If the ZIP is compressed, either the dataset is actually zarr (and we need to add DEFLATE to the list of codecs) or a datatype where we have one chunk per original file, like the earthdata massive set of geoTIFFs (the codec chain would be imagecodecs.tiff->DEFLATE). But of course, you don't gain a lot compressing data that is already internally compressed. DEFLATE/zip-compress I believe is the same as numcodecs.Zlib.

**Comment by martindurant** [comment]
This is what I have so far: https://gist.github.com/martindurant/95a5c67a1a1cd9ea6c67bd515e331613

The `ds2` at the end is an xarray dataset for the first member of the smaller file. It loads pretty well, even with the 340kB chunks. Scanning didn't take very long from my laptop. I haven't looked at the other files yet, but there's no principled reason it should fail.

**Comment by martindurant** [comment]
I don't know about embedding the tar info in the output JSON, but the workflow here is sound, and we can do it for all the files in the two big TARs. We should be able to contain the extra steps in a pre- or post-process function to multizarrtozarr.

For now, I updated my gist to do the three files in ice.tar . The total size of the produced JSON file is ~3MB, uncompressed.

```
<xarray.Dataset>
Dimensions:               (time_counter: 3, y: 6540, x: 6560, axis_nbounds: 2)
Coordinates:
    nav_lat               (y, x) float32 dask.array<chunksize=(13, 6560), meta=np.ndarray>
    nav_lon               (y, x) float32 dask.array<chunksize=(13, 6560), meta=np.ndarray>
    time_centered         (time_counter) object dask.array<chunksize=(1,), meta=np.ndarray>
  * time_counter          (time_counter) object 2014-01-01 12:00:00 ... 2014-...
Dimensions without coordinates: y, x, axis_nbounds
Data variables: (12/31)
    corstrx               (time_counter, y, x) float32 dask.array<chunksize=(1, 13, 6560), meta=np.ndarray>
    corstry               (time_counter, y, x) float32 dask.array<chunksize=(1, 13, 6560), meta=np.ndarray>
    dssh_dx               (time_counter, y, x) float32 dask.array<chunksize=(1, 13, 6560), meta=np.ndarray>
    dssh_dy               (time_counter, y, x) float32 dask.array<chunksize=(1, 13, 6560), meta=np.ndarray>
    fsticp                (time_counter, y, x) float32 dask.array<chunksize=(1, 13, 6560), meta=np.ndarray>
    intstrx               (time_counter, y, x) float32 dask.array<chunksize=(1, 13, 6560), meta=np.ndarray>
    ...                    ...
    time_centered_bounds  (time_counter, axis_nbounds) object dask.array<chunksize=(1, 2), meta=np.ndarray>
    time_counter_bounds   (time_counter, axis_nbounds) object dask.array<chunksize=(1, 2), meta=np.ndarray>
    utau_ai               (time_counter, y, x) float32 dask.array<chunksize=(1, 13, 6560), meta=np.ndarray>
    utau_oi               (time_counter, y, x) float32 dask.array<chunksize=(1, 13, 6560), meta=np.ndarray>
    vtau_ai               (time_counter, y, x) float32 dask.array<chunksize=(1, 13, 6560), meta=np.ndarray>
    vtau_oi               (time_counter, y, x) float32 dask.array<chunksize=(1, 13, 6560), meta=np.ndarray>
Attributes:
    CASE:              DELTA
    CONFIG:            SEDNA
    Conventions:       CF-1.6
    description:       ice variables
    output_frequency:  1d
    start_date:        20090101
    title:             ice variables
    uuid:              88a97ec9-304c-42e6-b894-2730b1a82b37
```
(apparent in-memory size: 14.7GB)

**Comment by martindurant** [comment]
Yes, this is something that has come up before. My recommendation so far, has been to encode the set of arguments that xarray needs into an intake entry, so that the end user doesn't need to know the details. We may revisit ways to store extra parameters and other metadata in the references file itself, although it runs the risk of having the same information in multiple places.

**Comment by martindurant** [comment]
The gridS dataset looks like:
```
<xarray.Dataset>
Dimensions:               (deptht: 150, time_counter: 4, axis_nbounds: 2,
                           y: 6540, x: 6560)
Coordinates:
  * deptht                (deptht) float32 0.4915 1.526 ... 5.45e+03 5.55e+03
    nav_lat               (y, x) float32 dask.array<chunksize=(13, 6560), meta=np.ndarray>
    nav_lon               (y, x) float32 dask.array<chunksize=(13, 6560), meta=np.ndarray>
    time_centered         (time_counter) object dask.array<chunksize=(1,), meta=np.ndarray>
  * time_counter          (time_counter) object 2014-01-01 12:00:00 ... 2014-...
Dimensions without coordinates: axis_nbounds, y, x
Data variables:
    deptht_bounds         (time_counter, deptht, axis_nbounds) float32 dask.array<chunksize=(1, 1, 2), meta=np.ndarray>
    time_centered_bounds  (time_counter, axis_nbounds) object dask.array<chunksize=(1, 2), meta=np.ndarray>
    time_counter_bounds   (time_counter, axis_nbounds) object dask.array<chunksize=(1, 2), meta=np.ndarray>
    vosaline              (time_counter, deptht, y, x) float32 dask.array<chunksize=(1, 1, 13, 6560), meta=np.ndarray>
Attributes:
    CASE:              DELTA
    CONFIG:            SEDNA
    Conventions:       CF-1.6
    description:       ocean T grid variables
    output_frequency:  1d
    start_date:        20090101
    title:             ocean T grid variables
    uuid:              fd15ea8b-f2f0-4243-9df3-3783b2166764
```
with, again, small chunks (302400 partitions in the vosaline variable)

How are the two datasets supposed to be combined? Are these independent variables? I see four timepoints in gridS and three in ice.

**Comment by martindurant** [comment]
@norlandrhagen

**Comment by martindurant** [comment]
A copy of the file I used is at https://gist.github.com/martindurant/d8fde3992326bde766af695b9fd60c18

**Comment by martindurant** [comment]
kerchunk does not currently have a facility to create archive zarr files, but your code would be welcome here, if you wished. The format used by kerchunk is simple JSON (which is what the code referred to in this thread makes) rather than parquet as with preffs, but a) that probably doesn't matter for the number of chunks you are considering and b) we will be working on parquet as a storage format soon, inspired by what preffs has done.

**Comment by martindurant** [comment]
Simple answer:

> both the creation of such tar-zarrs and its indexing and accessing are within the scope of kerchunk?

yes

**Comment by rabernat** [comment]
Just seeing this issue

> I haven't used kerchunk yet, so my question is if both the creation of such tar-zarrs and its indexing and accessing are within the scope of kerchunk?

Zarr is mostly useful for indexing and referencing data that has already been written without having to copy it. If you are _writing new data_, why is kerchunk needed? Can you just use zarr to copy the data to a new store?

**Comment by martindurant** [comment]
You may well want to distribute a dataset as a TAR or .nc files, and put this in the cloud. You end up with far fewer files listed in the storage than copying the files directly, which can be important. So some download it, some use kerchunk access. Makes sense to me.

**Comment by martindurant** [comment]
As to zarr-in-tar, this is a hedge against the many many files that zarr can make. Kerchunk will give you concurrent access to the components, where a store based on fsspec/TarFileSystem will not.

**Comment by pbranson** [comment]
Thanks for these examples, I have been using zarr-in-zip for HPC workflows, I am keen to publish a dataset of zipped-zarrs to a publicly available object store to allow for both download and direct (kerchunk) access.

I have tested URL chaining with 
```
ds = xr.open_zarr('zip://::s3://bucket/data.zarr.zip',chunks='auto')
```
and this works OK with the fsspec debug indicating that it doesnt load the full dataset. 

Looking at the updates in #261 it seems like if the tar/zip contains one of the implemented file formats the example at https://fsspec.github.io/kerchunk/advanced.html#archive-files will work. However, I can't quite work out how to use this when the archive contains a zarr. 

What I like about this approach is that *maybe* the sidecar json references aren't needed when the zip header can be read and mapping created, but may that logic would need to be put in a separate intake driver.

**Comment by martindurant** [comment]
Agreed, when you have a zarr-in-zip, the zip's own index area is very much like kerchunk's reference set as a separate file. On major difference, though, is that you will get concurrent access on filesystems that support it, but not with ZIP. That won't matter in the case that you have one native chunk per dask partition, since dask's parallelism will still work, however it might make a big difference in some situations.

> I can't quite work out how to use this when the archive contains a zarr.

We can figure it out, maybe in another issue! One trick, is that if the chunks are compressed by ZIP (*not* a good idea, since zarr's codecs are better), we have to account for it as an array compressor.

**Comment by pbranson** [comment]
Thanks @martindurant, create a new issue!
