### ISSUE TITLE
IndexError with kerchunk.tiff.tiff_to_zarr

### ISSUE THREAD

**Issue by Break00** [fsspec/kerchunk#252]
The error were encountered using kerchunk version 0.0.9 on Python 3.9.13.  How can I fix this?

import ujson
import zarr
import kerchunk.tiff

out = kerchunk.tiff.tiff_to_zarr(r'./example.tif')

with open(r'./example.json',"w") as of:
    ujson.dump(out, of)

The notebook here: https://github.com/Break00/notebook/blob/main/tiff_kerchunk/example.ipynb
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In [13], line 5
      2 import zarr
      3 import kerchunk.tiff
----> 5 out = kerchunk.tiff.tiff_to_zarr(r'./example.tif')
      7 with open(r'./example.json',"w") as of:
      8     ujson.dump(out, of)

File ~/.local/lib/python3.9/site-packages/kerchunk/tiff.py:41, in tiff_to_zarr(urlpath, remote_options, target, target_options)
     39 if not k.endswith("metadata"):
     40     continue
---> 41 met = getattr(tif, k, None)
     42 try:
     43     d = dict(met or {})

File /opt/tljh/user/lib/python3.9/functools.py:993, in cached_property.__get__(self, instance, owner)
    991 val = cache.get(self.attrname, _NOT_FOUND)
    992 if val is _NOT_FOUND:
--> 993     val = self.func(instance)
    994     try:
    995         cache[self.attrname] = val

File /opt/tljh/user/lib/python3.9/site-packages/tifffile/tifffile.py:6178, in TiffFile.mdgel_metadata(self)
   6176     tags = self.pages.first.tags
   6177 else:
-> 6178     page = cast(TiffPage, self.pages[1])
   6179     if 33445 in page.tags:
   6180         tags = page.tags

File /opt/tljh/user/lib/python3.9/site-packages/tifffile/tifffile.py:6919, in TiffPages.__getitem__(self, key)
   6917     if key == 0:
   6918         return cast(TiffPage, pages[key])
-> 6919     return getitem(key)
   6921 if isinstance(key, slice):
   6922     start, stop, _ = key.indices(2**31 - 1)

File /opt/tljh/user/lib/python3.9/site-packages/tifffile/tifffile.py:6870, in TiffPages._getitem(self, key, validate, cache, aspage)
   6868     key %= len(self)
   6869 elif self._indexed and key >= len(pages):
-> 6870     raise IndexError(f'index {key} out of range({len(pages)})')
   6872 tiffpage = TiffPage if aspage else self._tiffpage
   6874 if key < len(pages):

IndexError: index 1 out of range(1)

**Comment by cgohlke** [comment]
> tifffile.py:6178, in TiffFile.mdgel_metadata(self)

That looks like an issue with tifffile. The `mdgel_metadata` property should return `None` for non-MD_GEL files.

**Comment by Break00** [comment]
> > tifffile.py:6178, in TiffFile.mdgel_metadata(self)
> 
> That looks like an issue with tifffile. The `mdgel_metadata` property should return `None` for non-MD_GEL files.

Thanks, Could you give me some advices to handle tiff with kerchunk.

**Comment by martindurant** [comment]
Actually, if such bad values contain no information, we can skip them at the kerchunk end. Can you try this:
```diff
--- a/kerchunk/tiff.py
+++ b/kerchunk/tiff.py
@@ -44,7 +44,10 @@ def tiff_to_zarr(urlpath, remote_options=None, target=None, target_options=None)
                 for k in dir(tif):
                     if not k.endswith("metadata"):
                         continue
-                    met = getattr(tif, k, None)
+                    try:
+                        met = getattr(tif, k, None)
+                    except Exception:
+                        continue
                     try:
                         d = dict(met or {})
```

(NB, this is relative to current main, so line numbers are a bit different)

**Comment by cgohlke** [comment]
> Actually, if such bad values contain no information, we can skip them at the kerchunk end. Can you try this:

Besides the issue in tifffile, which will be fixed in the next version, this patch is a good idea because metadata parsing can fail for many reasons.

**Comment by martindurant** [comment]
https://github.com/fsspec/kerchunk/pull/257
