### ISSUE TITLE
Grib2 scan_grib: Dimensions are Out of Order

### ISSUE THREAD

**Issue by keltonhalbert** [fsspec/kerchunk#259]
I've been attempting to follow [this kerchunk grib2 example using HRRR data](https://nbviewer.org/gist/peterm790/92eb1df3d58ba41d3411f8a840be2452), but I have encountered an interesting issue that prevents me from being able to use the Dataset in my intended manner due to the mis-naming (or mis-ordering) of X and Y dimensions for arrays. 

Running the example_combine from the documentation (copied below) and printing the dataset shows the issue: the arrays are labeled as ```(time, x, y)```, but the actual ordering of the grib2 data is ```(time, y, x)```. 1799 is the X extent of the domain and 1059 is the Y extent of the domain, yet in the dimensions, they are labeled opposite.  Attempting to perform operations on the Dataset when working with X and Y coordinate names doesn't work because of this behavior. 

I've attempted manually modifying the kerchunk/grib2.py file to re-order occurrences of ```["x", "y"]```, but sadly the solution doesn't appear to be that simple. Any ideas on how to make sure that the array dimensions are labeled correctly? 

## Script Output
```
<xarray.Dataset>
Dimensions:            (time: 1, x: 1059, y: 1799, heightAboveGround: 1)
Coordinates:
  * heightAboveGround  (heightAboveGround) int64 2
  * time               (time) datetime64[ns] 2019-01-01T22:00:00
Dimensions without coordinates: x, y
Data variables:
    2d                 (time, x, y) float64 dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    2r                 (time, x, y) float64 dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    2sh                (time, x, y) float64 dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    2t                 (time, x, y) float64 dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    latitude           (x, y) float64 dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (x, y) float64 dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    pt                 (time, x, y) float64 dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
Attributes:
    centre:             kwbc
    centreDescription:  US National Weather Service - NCEP
    edition:            2
    subCentre:          0
```

## Example Script
```
import xarray as xr
import fsspec
from kerchunk.grib2 import scan_grib
def example_combine(
    filter={"typeOfLevel": "heightAboveGround", "level": 2}
):  # pragma: no cover
    """Create combined dataset of weather measurements at 2m height

    Ten consecutive timepoints from ten 120MB files on s3.
    Example usage:

    >>> tot = example_combine()
    >>> ds = xr.open_dataset("reference://", engine="zarr", backend_kwargs={
    ...        "consolidated": False,
    ...        "storage_options": {"fo": tot, "remote_options": {"anon": True}}})
    """
    from kerchunk.combine import MultiZarrToZarr, drop

    files = [
        "s3://noaa-hrrr-bdp-pds/hrrr.20190101/conus/hrrr.t22z.wrfsfcf01.grib2",

    ]
    so = {"anon": True, "default_cache_type": "readahead"}

    out = [scan_grib(u, storage_options=so, filter=filter) for u in files]
    out = sum(out, [])
    mzz = MultiZarrToZarr(
        out,
        remote_protocol="s3",
        preprocess=drop(("valid_time", "step")),
        remote_options=so,
        concat_dims=["time", "var"],
        identical_dims=["heightAboveGround", "latitude", "longitude"],
    )
    return mzz.translate()

def main():
    d = example_combine()

    fs = fsspec.filesystem("reference", fo=d, remote_protocol='s3', remote_options={'anon':True})
    m = fs.get_mapper("")
    ds = xr.open_dataset(m, engine="zarr", backend_kwargs=dict(consolidated=False),
                      chunks={'valid_time':1})
    print(ds)

if __name__ == "__main__":
    main()
```

**Comment by martindurant** [comment]
Maybe this is the same as https://github.com/fsspec/kerchunk/pull/249 ? What exact version of kerchunk do you have?

**Comment by keltonhalbert** [comment]
It could be similar, and I did see that issue, but I wasn't entirely sure if they are related and by how much since the HRRR grid is different form the GFS. Because of #249, I installed kerchunk from the main branch in case it was fixed - ```0.0.9+41.gda0bd22.dirty```. However, the issue was still present. 

If there is a way to hard-code the correct dimensions as a stopgap, I'd be fine with that in the intermediate... or if there are other ways I can contribute a fix via a PR, I'd be more than happy to! My initial attempts to brute force it haven't succeeded yet though.

**Comment by mpiannucci** [comment]
Yeah HRRR uses a lambert grid so it *should* have been unaffected by the work I did. Maybe the lambert grid type needs the same treatment? or maybe there was a side effect i was unaware of

**Comment by rsignell-usgs** [comment]
@peterm790 what say ye?

**Comment by keltonhalbert** [comment]
An interesting wrinkle is that that the Notebook example I used for this code also shows the [the same issue](https://nbviewer.org/gist/peterm790/92eb1df3d58ba41d3411f8a840be2452) - if you look at the dimensions in the notebook cells, they are also  ```(time, x, y)``` rather than the appropriate ```(time, y, x)```. I'm not sure when relative to the LL changes this notebook was created/run, but I just wanted to point it out in case the mislabeling of dimensions was previous behavior. 

What's weird is the actual dim sizes are appropriate - it seems to be just a mis-naming of those dimensions.

**Comment by martindurant** [comment]
I will remain generally stumped unless we can find a definitive way to derive which dimension length and name are which from the attributes of the grib dataset. One assumes xarray does this internally - unless there is simply a lookup mapping the various projections as specific cases.

**Comment by mpiannucci** [comment]
Looking at cfgrib https://github.com/ecmwf/cfgrib/blob/b2fc0edb27abfcfeef950563a89f98709abd11c1/cfgrib/dataset.py#L366 You can see that lambert is NON_DIMENSIONAL. If we look at dataset.py for cfgrib the coords look like they are encoded as lat/lng to me https://github.com/ecmwf/cfgrib/blob/b2fc0edb27abfcfeef950563a89f98709abd11c1/cfgrib/dataset.py#L386
![Screenshot 2022-12-08 at 2 52 58 PM](https://user-images.githubusercontent.com/1832671/206553946-03ffa960-245e-423b-b9b0-b63b3fc24b64.png)

In general ive found that grib data is encoded as (lat, lng), which is (row, col)

**Comment by martindurant** [comment]
I would be extremely happy if someone could provide the incantation that gets this correct, with solid tests for all the cases :|

**Comment by keltonhalbert** [comment]
I'd love to help where I can, but my experience with xarray, zarr, and cfgrib is more on the high-level side than the dataset manipulation side.  Am I correct in understanding that the following lines are where the logic needs to be applied? My naïve idea at a solution would be to match the dimension lengths to their grib names, and set the dimension order accordingly. I can do some experimenting and testing, and even make a PR if I get anywhere... or an alternative solution could be to copy the cfgrib dataset.py logic?

https://github.com/fsspec/kerchunk/blob/f4159d0c5ed8f504aa7fb2972c4377afbaefbf10/kerchunk/grib2.py#L179-L223

Are there specific tests that need passing? I can obviously test with the HRRR and GFS data - are there known cases where the grib data is in column-major order instead of row-major order? Are there other requirements a fix would need to consider, or would the primary requirement be to ensure that #249 remains fixed?

Sorry for playing 20 questions - just want to be able to help in any way I can :)

**Comment by mpiannucci** [comment]
As far as I know, we just have to update the dimension labels in kerchunk. Which starts with line 179 you linked to. 

As for test cases, this I know less about, but as far as I know all grib data from noaa is row major anyways. 

I am happy to help anyway as well, I already did the same thing for regular coords, should be the same thing for irregular coords

**Comment by keltonhalbert** [comment]
I quickly [forked the main branch](https://github.com/keltonhalbert/kerchunk) and swapped the X and Y dimension labels, and then re-generated my json files. At first glance it appears to work, fixing the issue. I also tested the code from #248, and realized that #248, #249, and this issue are indeed related. 

In short, #248 and #249 were because, as @mpiannucci hypothesized, kerchunk has always been backwards with the ```["x", "y"]``` coordinate labeling and indexing. Reverting #249, changing the order of ```["x", "y"]``` to ```["y", "x"]```, and swapping the following lines appears to fix both my issue, and the issue with the GFS output. 

Replace
https://github.com/fsspec/kerchunk/blob/f4159d0c5ed8f504aa7fb2972c4377afbaefbf10/kerchunk/grib2.py#L197-L223
with
```
                if isinstance(x, np.ndarray) and x.size == vals.size:
                    if (
                        m["gridType"]
                        in cfgrib.dataset.GRID_TYPES_2D_NON_DIMENSION_COORDS
                    ):
                        dims = ["y", "x"]
                        x = x.reshape(vals.shape)
                    else:
                        dims = [coord]
                        if coord == "latitude":
                            x = x.reshape(vals.shape)[:, 0].copy()
                        elif coord == "longitude":
                            x = x.reshape(vals.shape)[0].copy()
                        inline_extra = x.nbytes + 1
```
I believe this should be the appropriate way for the variables to be indexed and labeled, as  grib2 data should (hypothetically?) always be a C-ordered array. This also simplifies some of the logic in scan_grib. 

If I haven't made any grievous errors and are in agreement on the fix, then I can submit the PR. But I wanted to discuss the fix and show the example output first to get feedback. 

## GFS output from #248 
```
Processing s3://noaa-gfs-bdp-pds/gfs.20221028/06/wave/gridded/gfswave.t06z.atlocn.0p16.f000.grib2...
Processing s3://noaa-gfs-bdp-pds/gfs.20221028/06/wave/gridded/gfswave.t06z.atlocn.0p16.f001.grib2...


<xarray.Dataset>
Dimensions:     (latitude: 331, longitude: 301, step: 1, surface: 1, time: 1,
                 valid_time: 1)
Coordinates:
  * latitude    (latitude) float64 55.0 54.83 54.67 54.5 ... 0.3332 0.1666 0.0
  * longitude   (longitude) float64 260.0 260.2 260.3 ... 309.7 309.8 310.0
  * step        (step) timedelta64[ns] 00:00:00
  * surface     (surface) int64 1
  * time        (time) datetime64[ns] 2022-10-28T06:00:00
  * valid_time  (valid_time) datetime64[ns] 2022-10-28T06:00:00
Data variables:
    mpww        (latitude, longitude) float64 dask.array<chunksize=(331, 301), meta=np.ndarray>
Attributes:
    centre:             kwbc
    centreDescription:  US National Weather Service - NCEP
    edition:            2
    subCentre:          0
<xarray.DataArray 'longitude' (longitude: 301)>
array([260.      , 260.166667, 260.333333, ..., 309.666667, 309.833333,
       310.      ])
Coordinates:
  * longitude  (longitude) float64 260.0 260.2 260.3 260.5 ... 309.7 309.8 310.0
Attributes:
    long_name:      longitude
    standard_name:  longitude
    units:          degrees_east


<xarray.DataArray 'latitude' (latitude: 331)>
array([55.      , 54.833333, 54.666666, ...,  0.333224,  0.166557,  0.      ])
Coordinates:
  * latitude  (latitude) float64 55.0 54.83 54.67 54.5 ... 0.3332 0.1666 0.0
Attributes:
    long_name:      latitude
    standard_name:  latitude
    units:          degrees_north
```

### HRRR Output from this issue
```
<xarray.Dataset>
Dimensions:            (valid_time: 1, y: 1059, x: 1799, heightAboveGround: 1,
                        step: 1, time: 1)
Coordinates:
  * heightAboveGround  (heightAboveGround) int64 2
  * step               (step) timedelta64[ns] 03:00:00
  * time               (time) datetime64[ns] 2022-11-04T18:00:00
  * valid_time         (valid_time) datetime64[ns] 2022-11-04T21:00:00
Dimensions without coordinates: y, x
Data variables:
    2d                 (valid_time, y, x) float64 dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    2r                 (valid_time, y, x) float64 dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    2sh                (valid_time, y, x) float64 dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    2t                 (valid_time, y, x) float64 dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    latitude           (y, x) float64 dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    pt                 (valid_time, y, x) float64 dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    unknown            (valid_time, y, x) float64 dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
Attributes:
    centre:             kwbc
    centreDescription:  US National Weather Service - NCEP
    edition:            2
    subCentre:          0
<xarray.DataArray 'longitude' (y: 1059, x: 1799)>
dask.array<open_dataset-9d39698bde0a2e44ce166d3e6145284clongitude, shape=(1059, 1799), dtype=float64, chunksize=(1059, 1799), chunktype=numpy.ndarray>
Dimensions without coordinates: y, x
Attributes:
    long_name:      longitude
    standard_name:  longitude
    units:          degrees_east


<xarray.DataArray 'latitude' (y: 1059, x: 1799)>
dask.array<open_dataset-9d39698bde0a2e44ce166d3e6145284clatitude, shape=(1059, 1799), dtype=float64, chunksize=(1059, 1799), chunktype=numpy.ndarray>
Dimensions without coordinates: y, x
Attributes:
    long_name:      latitude
    standard_name:  latitude
    units:          degrees_north
```

**Comment by mpiannucci** [comment]
That looks right to me!!
