### ISSUE TITLE
Extracting Kerchunk jsons from NetCDF removes data variables

### ISSUE THREAD

**Issue by drentawc** [fsspec/kerchunk#260]
Hello, I am researching and testing the cloud optimization of NetCDF access using kerchunk. I have been working with it for a few weeks but just recently found this tutorial : https://github.com/lsterzinger/2022-esip-kerchunk-tutorial/blob/main/01-Create_References.ipynb, and it had everything I needed to further my testing. I am generating the kerchunk jsons exactly how is described on the Kerchunk documentation and on that tutorial but when accessing the reference dataset through xarray it is missing major variables such as SST and DQF which is needed for the plot I am trying to create. I have included a reference json that I created, as well as the combined json file for any further debugging. Because of GitHub attachment limits I can't include the NetCDF but an example file can be found here https://noaa-goes16.s3.amazonaws.com/ABI-L2-SSTF/2022/001/00/OR_ABI-L2-SSTF-M6_G16_s20220010000205_e20220010059513_c20220010105222.nc. It is one of the same kind used in the tutorial.

Here is the method I am currently using to generate the jsons:
    
for file in flist:
        so = dict(
            mode="rb", anon=True, default_fill_cache=False, default_cache_type="none"
        )
        with fsspec.open(file, **so) as inf:
            h5chunks = kerchunk.hdf.SingleHdf5ToZarr(inf, file, inline_threshold=300)
            with open(f"jsons/{file.split('/')[-1]}.json", 'wb') as outf:
                outf.write(ujson.dumps(h5chunks.translate()).encode())

[jsons.zip](https://github.com/fsspec/kerchunk/files/10170087/jsons.zip)

**Comment by martindurant** [comment]
I downloaded the file in the link and ran kerchunk on it locally.
```
out = kerchunk.hdf.SingleHdf5ToZarr("OR_ABI-L2-SSTF-M6_G16_s20220010000205_e20220010059513_c20220010105222.nc").translate()
m = fsspec.get_mapper("reference://", fo=out)
ds = xr.open_dataset(m, engine="zarr")
```
and I get the same 42 variables in `ds` as when directly opening the .nc with xarray. 

For the JSON you sent, exactly the two `{'DQF', 'SST'}` variables appear to be missing. It would be good to see your exact code.

If I process the one file at its original location, I get all the variables. Here is my code:
```python
url = "s3://noaa-goes16/ABI-L2-SSTF/2022/001/00/OR_ABI-L2-SSTF-M6_G16_s20220010000205_e20220010059513_c20220010105222.nc"
out = kerchunk.hdf.SingleHdf5ToZarr(url, storage_options={"anon": True}).translate()
m = fsspec.get_mapper("reference://", fo=out, remote_options={"anon": True})
ds = xr.open_dataset(m, engine="zarr")
assert len(ds) == 42
assert "DQF" in ds and "SST" in ds
```

**Comment by drentawc** [comment]
Thanks for that help, I updated kerchunk, xarray, h5py, and fsspec and retried your code/ what I had and it all worked perfectly so not sure exactly what was causing it but I am good to go now.

**Comment by ShaneMill1** [comment]
I actually just ran into this exact issue and for me it ended up being the version of zarr I had. I updated the version and was good to go.

**Comment by martindurant** [comment]
Weird! Glad it worked.
