### ISSUE TITLE
Proposal: Combine multiple kerchunk’d datasets accordingly to time info contained within the filename 

### ISSUE THREAD

**Issue by pl-marasco** [fsspec/kerchunk#285]
**overall situation:**

some data are produced without any embedded info regarding the temporal information; the only way this info is given is through the name of the file (ex: spectral_197001012359_). More info on this in #184 
The only way to use the time information to combine multiple kerchunk’s datasets into a single logical aggregate dataset over time is to use the `.coo_map` in combination with a regex `re.Pattern`. The returned value will not be in a `Datetime64` format even if users try to coerce the string through `.coo_dtyes`. As the time info will be converted to a 'str'the only way to treat properly is open the .zarr dataset,  defining a preprocess_zarr function as suggested by @rbanick in https://github.com/fsspec/kerchunk/issues/184#issuecomment-1387254547

**proposal:**

Add the possibility to define a `.coo_map` selector (ex: "time:{re.Pattern}" ) that will be applied to the filename and will return proper `DateTime` info.

**requirements:**

as time formats can be quite complex, a new optional parameter `time_format` would be needed. Additional info such as the cftime's  `units` and the `calendar` has to be defined to achieve a proper conversion without radically modifying the actual code. 

@martindurant  in response to the suggestion of using the general function I've the impression that this could facilitate the use as this scenario, in the EO world, is pretty common. For my need I've already done everything but, before create a PR, I thought it would have be nicer to discuss here before.

**Comment by martindurant** [comment]
Kerchunk combine does allow for an escape hatch in coo_map for complex manipulations that might be required to get the correct value for a coordinate:
```
            - a function with signature (index, fs, var, fn) -> value, where index is an int
              counter, fs is the file system made for the current input, var is the variable
              we are probing may be "var") and fn is the filename or None if dicts were used
              as input
```

so in this case that would be

```python
def fn_to_time(index, fs, var, fn):
    import re
    import datetime
    subst = re.match("[a-z]+_(\d+)_", fn).groups()[0]
    return datetime.datetime.strptime('197001012359', '%Y%m%d%H%M')
```
or just the function `pd.to_datetime` instead of strptime.


I would be happy to see more general coordinate conversion functions like you suggest, but the API complexity will only go up. Perhaps we could do well to make a new module with all the named "selector" types as standalone functions, which would also allow them to be better tested independently.

**Comment by pl-marasco** [comment]
You are absolutely right mentioning the 'function with signature' as the most elegant approach but, talking with others, I had the impression that general users consider it a little bit too complex.  
The faster solution could be to add a specific example in the documentation; this could help users immediately. In the next days I'll make a PR for it. 

Regarding your proposal how you would call the standalone functions? how you would name the module? 

Meanwhile [here](https://github.com/pl-marasco/kerchunk-orig/commit/596147328628a2fe3a900b367c260a9963e6714f) you can have a look at what I've done for my needs.
