### ISSUE TITLE
KeyErrors

### ISSUE THREAD

**Issue by pl-marasco** [fsspec/kerchunk#291]
I'm processing a dataset and from time to time, over some of the files that compose the archive, I get an error that more or less is always structured like this one:

```Traceback (most recent call last):
  ...
  File "\lib\site-packages\kerchunk\combine.py", line 483, in translate
    self.second_pass()
  File "\lib\site-packages\kerchunk\combine.py", line 469, in second_pass
    self.out[key] = bits[fn]
KeyError: 'Oa03_toc_error/9.2'
```
Errors all the time rise up by the `self.out[key] = bits[fn]` . Specific DataArray highlited in the KeyError varing almost all the time the error is raise.  
As the KeyError seems to be somehow related to the chunking organization I've tested if the files are corrupted but don't seem to be the case. 

If I remove the problematic files everything goes as expected;but,  unfortunately, that's not a real option. 

Kerchunk version 0.1.0

**Comment by martindurant** [comment]
Were there any warnings during processing the source files with kerchunk.hdf? That should have told you if some buffers failed to turn into keys for some reason.

> an error that more or less is always structured like this one

The does same input always produce the same error, or does the key referenced appear to change each time?

**Comment by pl-marasco** [comment]
Here is the test I've conducted up to now. 

- fetched from scratch problematic files 
- recreated reference files (no errors, tested as well with `pdb` ) 
- tested different `inline_threshold` [ 0, 100, 250, 300, 500, 1000]
- read single reference files to test if the readability per single file is ok (no issue raised)

For every single file, the error raised is always the same and always points to the same /chunk(?) within the DataArray (ex: file1:  Oa03_toc_error/9.2, file2: AC_process_flag/4.0)
All the non problematic fils can be packed easily; so seems really that's a matter of something within specific files.  
If needed I can share problematic files as are quite small.

**Comment by martindurant** [comment]
Yes, I am happy to look at one of your files.

**Comment by pl-marasco** [comment]
You should have access to the repository; there is as well the code to test it.  Unfortunatelly I've to work on Win OS so most probably you will have to adapt the paths.
