### ISSUE TITLE
"templates" no longer appearing in kerchunk files?

### ISSUE THREAD

**Issue by agstephens** [fsspec/kerchunk#297]
Hi folks,

Thanks for kerchunk - I think it's great.

I have just upgraded to v0.1.0 (from v0.0.9) and I notice that the `"templates"` section no longer appears in my single kerchunk file. I am creating it from:

```
kerchunk.hdf.SingleHdf5ToZarr(filepath, inline_threshold=500).translate()
```

Is the "templates" feature being deprecated, or do I just need a different argument in my code? Many thanks

**Comment by martindurant** [comment]
I think the feeling was, that any compression of the JSON does a really good job of finding and deduplicating URLs. I usually recommend Zstd, which promises roughly equal-time decompression for any compression level, so you only need to choose how much up-front time you spend when writing the file. In the long run, parquet storage will be the solution to large reference sets.

**Comment by agstephens** [comment]
Hi @martindurant, thanks - that's useful to know. Can you point me to an example that uses Zstd. I'm not familiar with it.

**Comment by martindurant** [comment]
Zstd can be installed via conda or your favourite system package manager. It can be used on the CLI:
```bash
$ zstd -19 filename
```
will produce filename.zstd
(19 is the strongest, very slow compression)

If you have zstandard (the python package) installed, then you can write streight to zstd without the intermediate file:
```python
refs = hdf.translate()
with fsspec.open("out.json.zstd", "wt", compression="zstd") as f:
    ujson.dump(f, refs)
```

When reading this again with ReferenceFS, be sure to include `compression="zstd"` in the target options.

**Comment by agstephens** [comment]
Thanks @martindurant, would I only need to apply the compression in the `MultiZarr` file - rather than any of the single files?

**Comment by martindurant** [comment]
If you only need to keep the final aggregated reference set, there's no need to compress the intermediate files. The template or lack of would not have affected this size of the final output anyway. MultiZarrToZarr lets you put the `compression=` kwarg directly into the `.translate()` method under storage_options.

**Comment by agstephens** [comment]
Thanks @martindurant, we'll add that! Much appreciated.

**Comment by agstephens** [comment]
Hi @martindurant, sorry for badgering you. I have got some code that now writes a `.zstd` file - which is smaller.
How do I read it into `xarray`, I'm trying:
```
import xarray as xr
mapper = fsspec.get_mapper("reference://", fo=output_uri, compression="zstd")
ds = xr.open_zarr(mapper)
```

What is the magic incantation that I need? Thanks

**Comment by agstephens** [comment]
Hi @martindurant, it looks like this works. Is it the recommended way to do it?

```
import xarray as xr
zstd_file = fsspec.open(output_uri, mode="rt", compression="zstd").open()
mapper = fsspec.get_mapper("reference://", fo=zstd_file)
ds = xr.open_zarr(mapper)
```

**Comment by martindurant** [comment]
That version is OK, but you could have saved one line
```
mapper = fsspec.get_mapper("reference://", fo=output_uri, tagret_options={"compression": "zstd"})
ds = xr.open_zarr(mapper)
```
or written everything on one line
```
ds = xr.open_zarr("reference://", 
    storage_options={
         dict(fo=output_uri, tagret_options={"compression": "zstd"})
    }
)
```
Which of these you find more readable is up to you!

Note that xr.read_zarr might get deprecated in favour of xr.open_dataset(..., engine="zarr") which, annoyingly from kerchunk's POV, has consolidated=True by default.

**Comment by agstephens** [comment]
Thanks @martindurant, that's great!
