### ISSUE TITLE
What is the best way to concatenate over time where files have different "time:units" string?

### ISSUE THREAD

**Issue by agstephens** [fsspec/kerchunk#302]
Hi, I have a number of cases in which the input NetCDF files have different `time:units` even though the files represent a valid time series. So far, if I combine them in Kerchunk, the code does not concatenate them because (I think) it sees different `time:units` in the attributes and considers them to be different.

For example, here are some files, with the main time components exposed:
```
FILE: /neodc/bicep/data/oceanic_export_production/v1.0/monthly/1998/BICEP_NCEO_ExportProduction_ESA-OC-L3S-MERGED-1M_MONTHLY_9km_mapped_199801-fv4.2.nc
                time:units = "days since 1998-01-16 00:00:00" ;
                time = 0 ;
FILE: /neodc/bicep/data/oceanic_export_production/v1.0/monthly/1998/BICEP_NCEO_ExportProduction_ESA-OC-L3S-MERGED-1M_MONTHLY_9km_mapped_199802-fv4.2.nc
                time:units = "days since 1998-02-16 00:00:00" ;
                time = 0 ;
FILE: /neodc/bicep/data/oceanic_export_production/v1.0/monthly/1998/BICEP_NCEO_ExportProduction_ESA-OC-L3S-MERGED-1M_MONTHLY_9km_mapped_199803-fv4.2.nc
                time:units = "days since 1998-03-16 00:00:00" ;
                time = 0 ;
```

Strategies I might employ:
1. Write a `preprocessor` to normalise the times before combining the Kerchunk dicts.
2. Try to use the coordinate/variable mapping capabilities in Kerchunk.

Do you have a recommended way of doing this? Thanks

**Comment by martindurant** [comment]
There is a specific option for CF time conversion in [MultiZarrToZarr](https://fsspec.github.io/kerchunk/reference.html#kerchunk.combine.MultiZarrToZarr)'s standard coordinate mappers : 
- ”cf:{var}”, interpret the value of var using cftime, returning a datetime. These will be automatically re-encoded with cftime, unless you specify an “M8[*]” dtype for the coordinate, in which case a conversion will be attempted.

so you would do something like `coo_map={"time": "cf:time"}` and you _may_ wish to also have `coo_dtypes={"time": "M8[s]"}`

**Comment by agstephens** [comment]
Thanks @martindurant, I thought you would probably have come across this one before. 

We'll have a play. 👍

**Comment by agstephens** [comment]
It works! Great!
