### ISSUE TITLE
`combine.auto_dask` doesn't loop over all batches

### ISSUE THREAD

**Issue by dougiesquire** [fsspec/kerchunk#306]
I think there's an bug in the [batch loop in `combine.auto_dask`](https://github.com/fsspec/kerchunk/blob/e235ddd96cf2311f413612b20469af4aab29a75b/kerchunk/combine.py#L677)

Currently, it loops over 

```python
tasks_per_batch = len(tasks) // n_batches

for batch in range(tasks_per_batch + 1):
    in_tasks = tasks[batch * tasks_per_batch : (batch + 1) * tasks_per_batch]
    ...
```
This will skip batches/tasks when `n_batches` > `tasks_per_batch`. Should the loop not be something like:
```python
tasks_per_batch = -(-len(tasks) // n_batches)

for batch in range(n_batches):
    in_tasks = tasks[batch * tasks_per_batch : (batch + 1) * tasks_per_batch]
    ...
```

Happy to submit a PR if you agree.

**Comment by martindurant** [comment]
It looks like you might be right. Can we make a test of auto_dask that would fail with the current code but pass with the change? Yes, a PR would be welcome.
