### ISSUE TITLE
Is it possible to open remote ensemble datasets?

### ISSUE THREAD

**Issue by zachsa** [fsspec/kerchunk#307]
Hi,

I'm assessing some approaches to publishing NetCDF files in a cloud-optimized format. I'm still new to NetCDF/Kerchunk and these concepts generally - apologies if I make no sense!

I'd like to create a single ensemble dataset accessible over HTTPS - is this possible? Looking at the Kerchunk library, I was wondering if I could place a JSON file, created by Kerchunk, in a folder with _n_ NetCDF files (the JSON fie would provide a unified view of all the NetCDFs in a cloud-optimized format). Both the Kerchunk JSON file and the NetCDFs are accessible via an HTTP-range respecting static file server.

Is it possible to open an ensemble dataset at a remote location (i.e. https://something.com/files/kerchunk-output.json)?

I think what I'm asking is whether I can do this

```js
import xarray as xr
ds = xr.open_dataset(
    "https://something.com/files/kerchunk-output.json", engine="zarr",
    backend_kwargs={
        "storage_options": {
            "fo": out,
            "remote_protocol": "s3",
            "remote_options": {"anon": True}
        },
        "consolidated": False
    }
)
# do analysis...
ds.velocity.mean()
```

**Comment by martindurant** [comment]
Yes, you can totally do this, it is normal. The JSON file and the original data files are the "target" and "remote" arguments in storage_options. For HTTP you probably need no extra options, but for other stores like s3 you might. There is no reason that the JSON and data files need to be in the same place - kerchunk was developed with the idea that you might not have write permission to the original data location.

**Comment by zachsa** [comment]
Thank you very much for such a quick response. Wonderful to hear it's possible!
