### ISSUE TITLE
`combine.MultiZarrToZarr` producing broken reference file

### ISSUE THREAD

**Issue by dougiesquire** [fsspec/kerchunk#310]
I have a set of netcdf4 files that I'm trying to generate a kerchunk reference file for. I can generate single-file references successfully using `kerchunk.hdf.SingleHdf5ToZarr`. However, combining these single-file references using `kerchunk.combine.MultiZarrToZarr` produces a combined reference file that is incorrect. Specifically, I can generate a combined reference json without error, but the contents are incorrect. I've not been able to work out the cause of the issue.

Some example data and a notebook demonstrating the issue can be found [here](https://github.com/dougiesquire/kerchunk_debug). The notebook can be run with binder [here](https://mybinder.org/v2/gh/dougiesquire/kerchunk_debug/HEAD?labpath=example.ipynb). To summarise, the following plot taken from the notebook compares the data accessed via netcdf4-python with that accessed via the single-file reference jsons and via the combined reference json. Reading the data via the single-file jsons gives the same result as netcdf4-python (the orange line is on top of the blue line). However, when the data are read via the combined json, the chunks are scrambled/missing.

![Screenshot 2023-03-01 at 4 52 40 pm](https://user-images.githubusercontent.com/42455466/222056478-dd73cd17-37ff-4abe-b28d-e540ba12098f.png)

**Comment by martindurant** [comment]
Please confirm that https://github.com/fsspec/kerchunk/pull/311 fixes this for you. I need to think of how to write a test against it, since this was not being caught. The issue was, that the chunk size is not the same in different variables, and the value in one was leaking to the key determination section of another.

**Comment by dougiesquire** [comment]
> Please confirm that #311 fixes this for you

It sure does - awesome, thanks!
