### ISSUE TITLE
Error when trying to open dataset with xarray

### ISSUE THREAD

**Issue by John-Ragland** [fsspec/kerchunk#316]
I am trying to create a json file (or in this specific case a dictionary) from a single hdf5 file stored on azure, and then open the dataset with xarray. I'm running into an error where the dataset only has the uuid as an attribute, but with no data variables.

This data is publicly available so this example should work for others as well.

```
import fsspec
import kerchunk.hdf
import xarray as xr

# Set the account name, container name, and file path
account_name = "dasdata"
container_name = "hdf5"
file_path = "South-C1-LR-95km-P1kHz-GL50m-SP2m-FS200Hz_2021-11-01T231114Z.h5"

# Set the blob URL using the fsspec AzureBlobFileSystem
url = f"az://{container_name}/{file_path}"
openfile = fsspec.open(url, account_name=account_name)

# Generate dictionary
h5chunks = kerchunk.hdf.SingleHdf5ToZarr(inf.open())
out = h5chunks.translate()

# open dataset with xarray
ds = xr.open_dataset("reference://", engine="zarr", backend_kwargs={
                    "consolidated": False,
                    "storage_options": {"fo": out, "remote_protocol": "az","remote_options": {"account_name":account_name}}
                    })
print(ds)
```

I get the output
```
<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
Attributes:
    uuid:     6b5fbdc4-ec25-4ecb-b5c6-b20138e155d0
```

the dictionary ```out```, seems to be correctly created, with a mapping from zarr chunk indices to slices of the hdf5 file.

Thanks for the help!

**Comment by martindurant** [comment]
kerchunk succesfully scans this data and produces the right output. The trouble is, the HDF5 file is *not* a netCDF4 dataset, which is what xarray expects. If you open the original with xarray, you get exactly the same output.

It loads fine in zarr alone, and produces a component tree like:
```
/
 └── Acquisition
     ├── Custom
     └── Raw[0]
         ├── Custom
         │   ├── GpBits (12000,) uint8
         │   ├── GpsStatus (12000,) uint8
         │   ├── PpsOffset (12000,) uint32
         │   └── SampleCount (12000,) int64
         ├── RawData (47500, 12000) int32
         └── RawDataTime (12000,) int64
```

How did you expect xarray to deal with this, what would your next analysis step be?

**Comment by John-Ragland** [comment]
Would you mind sharing the code you used to open the dataset in zarr?

The end goal for analysis is to be able to do distributed computations with dask with the original hdf5 file format.

I was hoping to be able to work with xarray, but since this is not a netCDF4 dataset, I guess it might not be compatible. I know that xarray can't handle unflat datasets, which I'm realizing this dataset is. If this works within zarr, then I can probably accomplish my goals within zarr without passing it along to xarray.

**Comment by martindurant** [comment]
```
h5chunks = kerchunk.hdf.SingleHdf5ToZarr(inf.open(), url) # note adding URL here
out = h5chunks.translate()


import zarr
z = zarr.open("reference://", storage_options={'fo': out})
```

The tree was produced using `print(z.tree())`, and you can access the components like `z["Acquisition"]["raw[0]"]`, etc.

Adding the `url` parameter when scanning means you don't need to re-supply this string every time you open the dataset.

**Comment by martindurant** [comment]
For parallel, chunkwise processing, see https://docs.dask.org/en/stable/generated/dask.array.from_zarr.html

**Comment by John-Ragland** [comment]
Okay, I'm running into another interesting problem with reading the data with zarr. When I load the data with zarr, I'm getting only zeros, but when I load the same file with hdf5, I'm able to load the actual values.

```
import fsspec
import kerchunk.hdf
import xarray as xr
import zarr
import h5py

# Set the account name, container name, and file path
account_name = "dasdata"
container_name = "hdf5"
file_path = "South-C1-LR-95km-P1kHz-GL50m-SP2m-FS200Hz_2021-11-01T231114Z.h5"

# Set the blob URL using the fsspec AzureBlobFileSystem
url = f"az://{container_name}/{file_path}"
openfile = fsspec.open(url, account_name=account_name)

# Generate dictionary
h5chunks = kerchunk.hdf.SingleHdf5ToZarr(openfile.open())
out = h5chunks.translate()

# Open with zarr
z = zarr.open("reference://", storage_options={'fo': out})
print(z['Acquisition']['Raw[0]']['RawData'][:5,:5])

# Open with h5py
hf = h5py.File(openfile.open())
print(hf['Acquisition']['Raw[0]']['RawData'][:5,:5])
```

output
```
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[3472221 3473106 3472831 3471105 3471869]
 [-425498 -424748 -428130 -428440 -429379]
 [-732567 -733165 -733989 -735417 -737383]
 [ 518432  516937  515703  512260  510987]
 [ 645204  644451  642124  639088  637703]]
```

**Comment by martindurant** [comment]
>> Adding the url parameter when scanning means you don't need to re-supply this string every time you open the dataset.

^ this is what you need to do; otherwise you need to supply `target=url` in your storage_options.

**Comment by John-Ragland** [comment]
Thanks. Apologies for the long discussion, I am new to fsspec and openning things up on object storage. This is where I'm at now.

```
import fsspec
import kerchunk.hdf
import zarr
import h5py

# Set the account name, container name, and file path
account_name = "dasdata"
container_name = "hdf5"
file_path = "South-C1-LR-95km-P1kHz-GL50m-SP2m-FS200Hz_2021-11-01T231114Z.h5"

# Set the blob URL using the fsspec AzureBlobFileSystem
url = f"az://{container_name}/{file_path}"
openfile = fsspec.open(url, account_name=account_name)

# Generate dictionary
h5chunks = kerchunk.hdf.SingleHdf5ToZarr(openfile.open(), url)
out = h5chunks.translate()

storage_options = {
    'fo':out,
    'remote_protocol':'az',
    'remote_options':dict(account_name=account_name)
}

z = zarr.open("reference://", storage_options=storage_options)

z['Acquisition']['Raw[0]']['RawData'][0,0]

```
The tree of the zarr file an be read, but when I try to read the file contents it throws the following error ```FileNotFoundError: ['Acquisition/Raw[0]/RawData/0.0']```

```
print(out['refs']['Acquisition/Raw[0]/RawData/0.0'])
```
gives the expected result: ```['az://hdf5/South-C1-LR-95km-P1kHz-GL50m-SP2m-FS200Hz_2021-11-01T231114Z.h5', 262144, 126115]```

**Comment by martindurant** [comment]
I ran your exact code, and it gave 3472221 as it should.

**Comment by John-Ragland** [comment]
was previously running
fsspec: 2022.3.0
zarr: 2.13.2

updated to
fsspec: 2023.3.0
zarr: 2.13.6

And now this works. Thanks for all of the help

Also FWIW, I was able to create a dask array using ```dask.array.from_zarr``` and pass that to xr.DataArray(). Sort of a work around hack, but I was able to do dask computations through xarray of this file.
