### ISSUE TITLE
Is it possible to create a kerchunk mapping that has different chunk sizes than the underlying file.

### ISSUE THREAD

**Issue by John-Ragland** [fsspec/kerchunk#327]
I am working on a dataset that is stored as multiple hdf5 files and want to be able to do cloud computing on this dataset. I am hoping to be able to use kerchunk and zarr to be able to easily utilize dask with the hdf5 files without the need to convert or store different copies of the data in a more cloud optimized format.

**A couple of problems that I've run into**
- For optimum performance with dask, chunk sizes are a function of machine specs, and the type of computations that you are trying to do.
- To use a different chunk size for a zarr store, an entirely new datastore must be created. Packages like rechunker work well but require you to store multiple copies of your data which becomes impractical for very large datasets.

I'm wondering if it's possible with kerchunk to define a mapping that combines an integer number of hdf5 (or other file format) chunks into a single zarr chunk. This would allow a new kerchunk mapping to be calculated for different computation contexts, but not have to store an entirely new version of the data. This figure summarizes what I'm trying to describe.

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/61983945/231515248-ffa3db8c-c557-4ae0-85ef-1e8d8cc7b856.png">

Not sure if this is possible, or could be possible in the future. Thanks in advance for any suggestions!

**Comment by martindurant** [comment]
The easiest thing you can do, if you are using xarray, is to specify the `chunks={...}` to be an integer multiple of the inherent chunk size. Then, these bigger chunks become dask partitions as in your diagram, and you need do nothing more.

**Comment by John-Ragland** [comment]
Yeah I think this solves the problem. Thanks!

**Comment by martindurant** [comment]
@rsignell-usgs , do you have a link to a place where you compared the performance for values of chunks= ?

**Comment by rsignell-usgs** [comment]
Yes, we illustrated 50% better performance using dask chunks that were 3x native chunks here: https://medium.com/pangeo/cloud-performant-netcdf4-hdf5-with-zarr-fsspec-and-intake-3d3a3e7cb935
