### ISSUE TITLE
UserWarning / NotImplementedError

### ISSUE THREAD

**Issue by rabernat** [fsspec/kerchunk#339]
Attempting to index the following file (should be public)

```
s3://earthmover-sample-data/hdf5/NEONDSTowerTemperatureData.hdf5
```

with the following code

```python
from kerchunk.hdf import SingleHdf5ToZarr
import fsspec

s3_url = "s3://earthmover-sample-data/hdf5/NEONDSTowerTemperatureData.hdf5"

with fsspec.open(s3_url) as infile:
    h5chunks = SingleHdf5ToZarr(infile, s3_url, inline_threshold=0)
    out = h5chunks.translate()
```

produces a rather uninformative warning

```
/srv/conda/envs/notebook/lib/python3.10/site-packages/kerchunk/hdf.py:436: UserWarning: The following excepion was caught and quashed while traversing HDF5

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/kerchunk/hdf.py", line 363, in _translator
    raise NotImplementedError
NotImplementedError

  warnings.warn(msg)
```

Following the code

https://github.com/fsspec/kerchunk/blob/f272c66c9ea23dd8aaef885f9b6fb1c1312d3813/kerchunk/hdf.py#L362-L363

Brings me to https://github.com/zarr-developers/numcodecs/issues/333. The issue is closed, suggesting that the underlying problem is resolved. If so, why are we getting a `NotImplementedError`.

Can someone explain what is going on?

**Comment by keewis** [comment]
looking at the date that issue was closed (Jan 13, 2023) and the last release date I could find (Dec 15, 2022), I would guess that the fix is simply not released yet? If that's the case, running the same code with the current state of `numcodecs` might work?

**Comment by martindurant** [comment]
In the top level, you have options 
```
    vlen_encode: ["embed", "null", "leave", "encode"]
        What to do with VLEN string variables or columns of tabular variables
        leave: pass through the 16byte garbage IDs unaffected, but requires no codec
        null: set all the strings to None or empty; required that this library is available
        at read time
        embed: include all the values in the output JSON (should not be used for large tables)
        encode: save the ID-to-value mapping in a codec, to produce the real values at read
        time; requires this library to be available. Can be efficient storage where there
        are few unique values.
```
where "embed" takes you to the NotImplemented branch for dtype=V (structured types). With the numcodecs issue closed, this code branch should now be implementable by using the JSON or msgpack codecs, but that hasn't propagated to kerchunk yet.
