### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by dcherian** [fsspec/kerchunk#371]
Once #364 goes in, can we have a release please? The last one was in May, it looks like.

Thanks!

**Comment by martindurant** [comment]
There was a release in August ( https://pypi.org/project/kerchunk/#history ) but it seems I failed to push the tag. one now.

**Comment by dcherian** [comment]
gentle ping here. there seem to be some nice and useful updates to grib and netcdf3 reading.

**Comment by martindurant** [comment]
It is release week! I'l try to put everything out by Friday.

**Comment by dcherian** [comment]
thanks!

**Comment by martindurant** [comment]
Is out on pypi, coming on conda-forge

**Comment by dcherian** [comment]
Thank you!
