### ISSUE TITLE
Parquet reference generation failing at translate step

### ISSUE THREAD

**Issue by zcobell** [fsspec/kerchunk#402]
Hi all - 

First of all, thanks for putting this software together. I was pointed to it by @rsignell-usgs and we are in the process of making a plan to see how we can best use it for many of our large datasets that we want to push out publicly.

I fully admit that my question below may be due to inexperience, so apologies if it is something simple I'm missing. I am attempting to use parquet references for some simulation data. The data is organized such that each simulation zarr'd and rechunked from its native format and now I'd like to create a set of reference that allows indexing the simulations by their id's. This works fine with the json file, but for a live case, the json can start to get fairly big, so we're looking into the parquet format as a possible solution for this. That's where the hangup occurs. I've put together a minimal example working from the documentation [here](https://fsspec.github.io/kerchunk/advanced.html#parquet-storage) to show where the code is getting hung up on the translate step. The notebook showing the usage [here](https://gist.github.com/zcobell/51fd8533894b70dddaa3da9a0fc6413e). 

And if interested, the source data is [here](https://twi-txfer.s3.amazonaws.com/sample_adcirc_zarr.7z) to try and replicate.

### Versions
python == 3.12.0
kerchunk == 0.2.2
fsspec == 2023.12.1
zarr = 2.16.1
ujson == 5.8.0
xarray = 2023.11.0

Your help is very much appreciated.

**Comment by martindurant** [comment]
Please ping me again after pydata madness has calmed down a bit.

It would be worthwhile `debug`ing to see what `value` is in the line that failed (perhaps `None`?).

**Comment by zcobell** [comment]
I've updated the above notebook to show what seems like it could be a bug in `LazyReferenceMapper.create` with a trivial fix, however, I'll reserve stating that definitively until I am able to solve the original error in this topic. The quick summary is:

```python
out = LazyReferenceMapper.create(
        record_size, root=url, fs=fs, categorical_threshold=categorical_threshold
    )
```

should become:

```python
out = LazyReferenceMapper.create(
        record_size=record_size, root=url, fs=fs, categorical_threshold=categorical_threshold
    )
```

to avoid:

```python
TypeError: LazyReferenceMapper.create() got multiple values for argument 'root'
```

**Comment by martindurant** [comment]
Yes, I'm sure the signature and docs of that method can be tightened up. In any case, explicit is good.

**Comment by martindurant** [comment]
So it seems we assume that the .zarray is always inlined, which would be true for any kerchunked dataset where we create the file (from hdf, grib, etc) with the sole exception of existing zarr datasets where they already exist. We could cover this case, but I would argue that ZarrToZarr should always inline .z* files as another way to solve it.

**Comment by zcobell** [comment]
Got it. I might be able to take a crack at implementing this over the next day or so if for no other reason than to bump into some walls to familiarize myself with some of the internals. If there was a particular way you'd had in mind to do this, I'm all ears.

**Comment by zcobell** [comment]
Updating the inlining to use the following code in `do_inline` in `utils.py` works well, but does slightly feel hacky. I'm guessing there may be a more robust way to do it than this. This has the effect of finding the `*.z` files that come in as a list object and always inlining them

```python
    get_keys = [
        k
        for k, v in out.items()
        if (isinstance(v, list) and len(v) == 3 and v[2] < threshold)
        or (
            isinstance(v, list)
            and len(v) == 1
            and isinstance(v[0], str)
            and v[0].split("/")[-1].startswith(".z")
        )
    ]
```

**Comment by martindurant** [comment]
I am quite sure that every scanner except zarr already inlines all .z files (or creates them) and has special code for this.

I think the code is fine; the two conditions could be annotated with comments ("small enough", "metadata").
