### ISSUE TITLE
NDFD grib2 file does not work as downloaded with scan_grib

### ISSUE THREAD

**Issue by mpiannucci** [fsspec/kerchunk#411]
NDFD grib2 files have a 21 character custom header before the `GRIB` start sequence which causes `scan_grib` to fail: 

Sequence (https://graphical.weather.gov/docs/grib_design.html#:~:text=The%20header%20contains%20the%20valid,the%20ASCII%20text%20%227777%22):
```
 ****0000696252****
YKAZ88 KWBN 060448

****0000014818****
YKAB06 KWBN 060448

GRIB
```

Source file: s3://noaa-ndfd-pds/wmo/waveh/2024/01/01/YKRZ98_KWBN_202401010149

![image](https://github.com/fsspec/kerchunk/assets/1832671/33b371bb-7722-4cec-9e29-59999390fc3f)

`scan_grib` could look for GRIB and start there instead of assuming the start sequence is GRIB possibly.

**Comment by martindurant** [comment]
> scan_grib could look for GRIB and start there instead of assuming the start sequence is GRIB possibly.

I suppose this is easy enough to code - will you have a go?

**Comment by mpiannucci** [comment]
Yeah I'll give it a shot :)
