### ISSUE TITLE
Restrict/target SingleHdf5ToZarr on/to Dataset of interest in a multi-Dataset HDF5/netCDF4 file

### ISSUE THREAD

**Issue by valeriupredoi** [fsspec/kerchunk#423]
Hi folks, first off I wanted to thank you lots for your great work on Kerchunk! We've been using it in our prototype package for a while now - nice, straightforward, and very convenient package, cheers :beer: 

Got a question to ask, please, and I have a rough solution for it as well:

**Problem summary**

- We are using Kerchunk to translate from netCDF4 (HDF5) files to a Zarr reference file, so we are using `SingleHdf5ToZarr`;
- files are read from an S3 bucket
- We are dealing with netCDF4 files that have order 100 variables inside them, but at any one conversion to Zarr ref call, one is only interested in a single variable, so that means one single HDF5 Dataset to be ingested in Kerchunk, and `SingleHdf5ToZarr`-ed
- what `SingleHdf5ToZarr` currently does is gets in the entire multi-Dataset file, and Kerchunks it, doing ops for all the Datasets, regardless I am interested in only one of them (as far as I understand)

**Bottleneck**

The current perceived behaviour of `SingleHdf5ToZarr` makes my things spend quite a bit in Kerchunk - actually, the entire runtime of my package, that includes a whole lot of other stuffs, is dominated at 90% by the time spent in Kerchunk, specifically HDF5 `visititems(callback)` method:
```
Kerchunk Visititems time 96.4
Time to Translate and Dump Kerchunks to json file 98.7
PyActiveStorage total time: 110s
```

**Possible solution**

I was wondering if it'd be possible to allow for a `var` kwarg to `SingleHdf5ToZarr` with implemented functionality like so:

```python
    def __init__(
        self,
        h5f: "BinaryIO | str",
        url: str = None,
        var: str = None,
        spec=1,
        inline_threshold=500,
        storage_options=None,
        error="warn",
        vlen_encode="embed",
    ):
    ...
        if var is not None:
            self._dataset = self._h5f[var]
    ...
    def _translator(self, name: str, h5obj: Union[h5py.Dataset, h5py.Group]):
    """Produce Zarr metadata for all groups and datasets in the HDF5 file."""
        if self._dataset is not None:
            h5obj = self._dataset
    ...
```

in fact, I've just tested this approach, and noticed a rough 25% decrease in runtime of `SingleHdf5ToZarr` for my test case, obviously this is a bit peasant-y and am sure there are better ways of restricting to desired only Datasets, but it's a start. What do you folks think? @martindurant et al. Cheers muchly in advance! :beers:

**Comment by martindurant** [comment]
Can I ask a clarification:
you want only one variable, but I presume you also want the coordinates associated with it? Or maybe all available coordinates? 

I don't see why we shouldn't be able to refine which parts of an HDF5 to store. There are probably various patterns that might be useful, though, beyond "single variable", so we should consider what's flexible enough without being too hard to use. I am thinking maybe a regex filter, to use any variable (+ coordinates) that match.

**Comment by valeriupredoi** [comment]
> so we should consider what's flexible enough without being too hard to use. I am thinking maybe a regex filter, to use any variable (+ coordinates) that match

That's a cool idea! You'll have a keen tester in me as soon as you guys have a prototype :grin:
