### ISSUE TITLE
Tutorial has mistakes

### ISSUE THREAD

**Issue by forestbat** [fsspec/kerchunk#427]
I'm trying to read data from minio server with code from [tutorial](https://pastebin.com/caRnH9WJ):
```
import xarray as xr

%%time
ds = xr.open_dataset("reference://", engine="zarr", backend_kwargs={
                    "consolidated": False,
                    "storage_options": {"fo": 'my_reference.json', 
                    "remote_protocol": "s3",
                    "remote_options": {"anon": True}}
                    })
print(ds)
```
However it crashed with this:
`TypeError: ZarrBackendEntrypoint.open_dataset() got an unexpected keyword argument 'remote_protocol'"`
The whold report is [here](https://pastebin.com/caRnH9WJ). 
So did the repository change when I don't know?

**Comment by martindurant** [comment]
This is a case of bad parentheses; indenting for clarity:
```
ds = xr.open_dataset(
    "reference://", 
    engine="zarr", 
    backend_kwargs={
        "consolidated": False,
        "storage_options": {"fo": 'my_reference.json', 
            "remote_protocol": "s3",
            "remote_options": {"anon": True}
        }
    }
)
```
has "remote_protocol" inside storage_options, which is within backend_kwargs. You see that remote_protocol does not to to the outermost call, which is what your exception is indicating.

Note that more recently, there is a "kerchunk" backend which makes this a bit less verbose
```
ds = xr.open_dataset(
    'my_reference.json', 
    engine="kerchunk", 
    backend_kwargs={
        "remote_protocol": "s3",
        "remote_options": {"anon": True}
    }
)
```

**Comment by forestbat** [comment]
> This is a case of bad parentheses; indenting for clarity:
> 
> ```
> ds = xr.open_dataset(
>     "reference://", 
>     engine="zarr", 
>     backend_kwargs={
>         "consolidated": False,
>         "storage_options": {"fo": 'my_reference.json', 
>             "remote_protocol": "s3",
>             "remote_options": {"anon": True}
>         }
>     }
> )
> ```
> 
> has "remote_protocol" inside storage_options, which is within backend_kwargs. You see that remote_protocol does not to to the outermost call, which is what your exception is indicating.
> 
> Note that more recently, there is a "kerchunk" backend which makes this a bit less verbose
> 
> ```
> ds = xr.open_dataset(
>     'my_reference.json', 
>     engine="kerchunk", 
>     backend_kwargs={
>         "remote_protocol": "s3",
>         "remote_options": {"anon": True}
>     }
> )
> ```

Thank for your reply，but in origin reports，brace of storage_options is completed:
![图片](https://github.com/fsspec/kerchunk/assets/23413915/4f4658b6-da79-4f9e-8ec3-6f196ad517e3)
May be when I'm copying the code, there is something wrong.

And there is another problem:
https://stackoverflow.com/questions/78074124/how-to-read-zarr-files-correctly-from-minio
Why the 3 methods all crashed? What's correct method to read zarr from minio server?
Hope your reply sincerely.

**Comment by martindurant** [comment]
The image looks very wrong indeed, the keys are not even in the right order, and why are all the quote marks escaped?

**Comment by forestbat** [comment]
> The image looks very wrong indeed, the keys are not even in the right order, and why are all the quote marks escaped?

I think this is because of pastebin's mechanism，it may add quotation mark to some strings. 
In fact，origin code doesn't look like this.

And can you cost a minute to read my another problem?
https://stackoverflow.com/questions/78074124/how-to-read-zarr-files-correctly-from-minio
Thank you for a lot.

**Comment by forestbat** [comment]
> This is a case of bad parentheses; indenting for clarity:
> 
> ```
> ds = xr.open_dataset(
>     "reference://", 
>     engine="zarr", 
>     backend_kwargs={
>         "consolidated": False,
>         "storage_options": {"fo": 'my_reference.json', 
>             "remote_protocol": "s3",
>             "remote_options": {"anon": True}
>         }
>     }
> )
> ```
> 
> has "remote_protocol" inside storage_options, which is within backend_kwargs. You see that remote_protocol does not to to the outermost call, which is what your exception is indicating.
> 
> Note that more recently, there is a "kerchunk" backend which makes this a bit less verbose
> 
> ```
> ds = xr.open_dataset(
>     'my_reference.json', 
>     engine="kerchunk", 
>     backend_kwargs={
>         "remote_protocol": "s3",
>         "remote_options": {"anon": True}
>     }
> )
> ```

I used kerchunk engine, however there is still mistake:
https://pastebin.com/FsBydUA1
```
vds = xr.open_dataset("gpm_gfs_nc.json", engine="kerchunk", backend_kwargs={
            "remote_protocol": "s3",
            "remote_options": conf.MINIO_PARAM
        })
```
`TypeError: ZarrBackendEntrypoint.open_dataset() got an unexpected keyword argument 'remote_protocol'`
So are you sure there is not any mistake in tutorial？Or there are some other changes which I don't know？

**Comment by forestbat** [comment]
Now I think this is a problem of xarray, so I will close this issue.
