### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jsignell** [fsspec/kerchunk#457]
Hi Martin :wave: 
Would it be possible to get a release please? 

VirtualiZarr is pinning down to avoid https://github.com/fsspec/kerchunk/issues/445 which is in 0.2.3 and 0.2.4 but fixed on main. Word is that xarray is releasing soon, so if kerchunk gets a release too all the deps over in virtualizarr land will be pointing to proper releases.

**Comment by martindurant** [comment]
I'll get #456 in, and then release

**Comment by martindurant** [comment]
0.2.5 on pypi now

**Comment by jsignell** [comment]
Thanks!

**Comment by TomNicholas** [comment]
Amazing thank you @martindurant !
