### ISSUE TITLE
NetCDF file has one time step, kerchunk-generated reference has nine time steps?

### ISSUE THREAD

**Issue by rsignell** [fsspec/kerchunk#465]
This is pretty strange -- I have a 64-bit offset NetCDF file locally (because it doesn't work to open these from S3) and when I open it in xarray, I see one time step.  

If I generate the references for this file, somehow I'm getting 9 time steps.     Any ideas?

This notebook should be reproducible -- the NetCDF files are on AWS Open Data:
https://gist.github.com/rsignell/1ec34cac9d4583bb44cbddcace2b8657

**Comment by martindurant** [comment]
I'll have a look this afternoon, but first guess would be, that the shape is smaller than the chunk size - so there is padding in the file which xarray knows to ignore, but kerchunk may need to be told (by me).

**Comment by rsignell** [comment]
I'm not sure I follow, but happy you will look at the problem later!

You agree that the references for all of these files should be identical, except for the time value, right?

So instead of creating 63,341 reference files, we only need to create one and then clone it with different time values!

**Comment by martindurant** [comment]
> You agree that the references for all of these files should be identical

I'm not sure you can guarantee that. One would think, with the same writer setup yes, since netCDF3 doesn't give too many options; but I don't know if it would be possible to, for example, reverse the order of two variables.
