### ISSUE TITLE
Got PermissionError: Access Denied when trying the example from the tutorial

### ISSUE THREAD

**Issue by b8raoult** [fsspec/kerchunk#472]
I am trying to run that tutorial https://fsspec.github.io/kerchunk/tutorial.html and I get `botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied` in the call to `fs.glob`

**Comment by martindurant** [comment]
On which line did you see this?

**Comment by martindurant** [comment]
@rsignell , I don't suppose you have an idea why the bucket "era5-pds" would have become inaccessible? It is still listed at https://registry.opendata.aws/ecmwf-era5/ .

**Comment by martindurant** [comment]
("nsf-ncar-era5" has similar but different anon-accessible data, and more of it if we are forced to jump)

**Comment by b8raoult** [comment]
This happens on the line:

 `fs.glob('s3://era5-pds/2020/*/data/air_pressure_at_mean_sea_level.nc')`

**Comment by martindurant** [comment]
I can confirm that the data seems to be unreachable. The dataset is marked as "deprecated", so perhaps it has been removed or is having other issues. If it doesn't resolve by itself shortly, we'll need to rewrite the tutorial with some other public data.

**Comment by b8raoult** [comment]
Ok, let's close the issue. I'd be interested if you know of any other dataset I could play with.

**Comment by martindurant** [comment]
Some here: https://fsspec.github.io/kerchunk/cases.html

but I have yet to compile a catalogue of interesting pre-kerchunked datasets or workflows that generate them, although some are around. As I mention above, the nsf-ncar-era5 bucket has loads of stuff, e.g., 
""s3://nsf-ncar-era5/e5.oper.an.pl/202403/e5.oper.an.pl.128_248_cc.ll025sc.2024032400_2024032423.nc" (225MB at rest, 3.6GB in memory) ->
```
<xarray.Dataset>
Dimensions:    (time: 24, level: 37, latitude: 721, longitude: 1440)
Coordinates:
  * latitude   (latitude) float64 90.0 89.75 89.5 89.25 ... -89.5 -89.75 -90.0
  * level      (level) float64 1.0 2.0 3.0 5.0 7.0 ... 925.0 950.0 975.0 1e+03
  * longitude  (longitude) float64 0.0 0.25 0.5 0.75 ... 359.0 359.2 359.5 359.8
  * time       (time) datetime64[ns] 2024-03-24 ... 2024-03-24T23:00:00
Data variables:
    CC         (time, level, latitude, longitude) float32 ...
    utc_date   (time) int32 ...
Attributes:
    DATA_SOURCE:          ECMWF: https://cds.climate.copernicus.eu, Copernicu...
    NETCDF_CONVERSION:    CISL RDA: Conversion from ECMWF GRIB 1 data to netC...
    NETCDF_VERSION:       4.9.2
    CONVERSION_PLATFORM:  Linux crhtc27 5.14.21-150400.24.46-default #1 SMP P...
    CONVERSION_DATE:      Mon 03 Jun 2024 07:36:39 PM MDT
    Conventions:          CF-1.6
    NETCDF_COMPRESSION:   NCO: Precision-preserving compression to netCDF4/HD...
    history:              Mon Jun  3 19:36:51 2024: ncks -4 -L 1 --baa=0 --pp...
```

**Comment by b8raoult** [comment]
Thanks. I'll close the issue.
