### ISSUE TITLE
Unable to append to already existing Kerchunk parquet store

### ISSUE THREAD

**Issue by sreesanjeevkg** [fsspec/kerchunk#487]
I attempted to append to an existing Parquet store, but encountered a KeyError with the following 
message:  Cloud_Retrieval_Fraction_16_Liquid[/.zarray](http://localhost:8888/.zarray).

Have included the code below for reference.

```
jsons_path = Path("/data/ssanjeev/temp/kerchunk_https_CLDPROP_D3_VIIRS_SNPP_2020-02-01_2020-03-01")
jsons_list = sorted(jsons_path.glob("*.json"))
print(f"found {len(jsons_list)} json files")
ref = LazyReferenceMapper("/data/ssanjeev/MultiZarrtoZarr/CLDPROP_D3_VIIRS_SNPP_2020-01-01_2020-02-01.parq")
batches = []
for i in range(0, len(jsons_list), 10):
    batch = list(islice(jsons_list, i, i + 10))
    batches.append([i, batch])
for i, batch in tqdm.tqdm(batches):
    print(i)
    print("append")
    MultiZarrToZarr.append(
            original_refs=ref,
            path=batch,
            coo_map={"time": lambda index, fs, var, fn: fnmeta.identify(fn)["begin_time"]},
            coo_dtypes={"time": np.dtype("M8[s]")},
            concat_dims=["time"],
        ).translate()
```
![Screenshot 2024-07-31 at 2 18 56 PM](https://github.com/user-attachments/assets/3a9701bd-8962-47a0-86a5-5cead3c4cc37)

but when I load the kerchunk using open_dataset it is working fine as expected.

```
ds = xr.open_dataset("/data/ssanjeev/MultiZarrtoZarr/CLDPROP_D3_VIIRS_SNPP_2020-01-01_2020-02-01.parq", engine="kerchunk", chunks="auto")
```

![Screenshot 2024-07-31 at 2 19 41 PM](https://github.com/user-attachments/assets/20efdeeb-1bb7-49b2-862f-ac4a165ddc2c)

@martindurant

**Comment by martindurant** [comment]
What exact version of fsspec do you have? I feel like I fixed something similar recently.

**Comment by sreesanjeevkg** [comment]
I am using the latest version of fsspec, Installed it again from git.

The fix you did earlier was for xr.open_dataset() - which is working fine; attached screenshot below for reference

![Screenshot 2024-07-31 at 3 58 34 PM](https://github.com/user-attachments/assets/e74e284b-9d96-46b8-9071-7d5138f0be58)

but the append functionality is throwing the error 

```
jsons_path = Path("/data/ssanjeev/temp/kerchunk_https_CLDPROP_D3_VIIRS_SNPP_2020-02-01_2020-03-01")
jsons_list = sorted(jsons_path.glob("*.json"))

# fs = fsspec.filesystem(
#             "reference",
#             fo="/data/ssanjeev/MultiZarrtoZarr/CLDPROP_D3_VIIRS_SNPP_2020-01-01_2020-02-01.parq"
#         )
parq = "/data/ssanjeev/MultiZarrtoZarr/CLDPROP_D3_VIIRS_SNPP_2020-01-01_2020-02-01.parq"
batches = []
for i in range(0, len(jsons_list), 10):
    batch = list(islice(jsons_list, i, i + 10))
    batches.append([i, batch])
for i, batch in tqdm.tqdm(batches):
    print(i)
    print("append")
    MultiZarrToZarr.append(
            original_refs=parq, # fs.get_mapper()
            path=batch,
            coo_map={"time": lambda index, fs, var, fn: fnmeta.identify(fn)["begin_time"]},
            coo_dtypes={"time": np.dtype("M8[s]")},
            concat_dims=["time"],
        ).translate()
```

![Screenshot 2024-07-31 at 4 02 20 PM](https://github.com/user-attachments/assets/6bfb461e-be0a-4687-bd3a-328165fb5778)

Maybe something to do with the implementation of LazyReferenceMapper ? because when I use 

`out = LazyReferenceMapper.create(root=str(self.parquetPath), fs=self.fs_local)` for the first time and then keep appending using the same out, the append() is working fine but when I need to append to an already existing parquet I come across this error.

**Comment by sreesanjeevkg** [comment]
@martindurant Any updates ?

**Comment by martindurant** [comment]
I haven't had a chance to look yet. Any chance of e standalone reproducer (no data file dependency)?

**Comment by sreesanjeevkg** [comment]
Let me check if I can put together a google colab notebook, 

These are the netcdf4 files,
https://ladsweb.modaps.eosdis.nasa.gov/search/order/4/CLDPROP_D3_VIIRS_SNPP--5111/2024-06-21..2024-07-05/DB/World

**Comment by sreesanjeevkg** [comment]
[KerchunkError.md](https://github.com/user-attachments/files/16460036/KerchunkError.md)

I have shared the notebook, Downloaded files from the link below

https://ladsweb.modaps.eosdis.nasa.gov/search/order/4/CLDPROP_D3_VIIRS_SNPP--5111/2024-06-21..2024-07-05/DB/World

I have the versions of fsspec and kercunk specified below.

```
fsspec                    2024.6.1.post8+g3ff5fca
kerchunk                  0.2.6.post17
```

From the notebook, i am not even able to read the parquet, getting the /.zarray error.

**Comment by sreesanjeevkg** [comment]
[KerchunkErrorAppend.md](https://github.com/user-attachments/files/16460184/KerchunkErrorAppend.md)

I have included a notebook for reproducing the error. I downloaded the first two files from 
https://ladsweb.modaps.eosdis.nasa.gov/search/order/4/CLDPROP_D3_VIIRS_SNPP--5111/2024-06-21..2024-07-05/DB/World

created parquet with the first netcdf4, and accessed it [worked fine] , but unable to append the next JSON to it.
