### ISSUE TITLE
Compressor is stored under filters in kerchunk >= 0.2.1

### ISSUE THREAD

**Issue by alistaireverett** [fsspec/kerchunk#489]
We locked our kerchunk version to 0.2.0 a little while ago and I've finally had time to really dig into it and see what's going on.

If we take this example netcdf file (zipped so I could upload it here): 
[test_NorKyst-800m_ZDEPTHS_avg_20240802T00Z.zip](https://github.com/user-attachments/files/16468034/test_NorKyst-800m_ZDEPTHS_avg_20240802T00Z.zip)

Running the following code snippet gives different results in kerchunk 0.2.0 and 0.2.1 where zlib was under compressor in 0.2.0 but is now moved under filters in >=0.2.1:
```python
from kerchunk.hdf import SingleHdf5ToZarr

h5chunks = SingleHdf5ToZarr("test_NorKyst-800m_ZDEPTHS_avg_20240802T00Z.nc")
print(h5chunks.translate()["refs"]["X/.zarray"])
```

Result in Kerchunk 0.2.0:

```json
{
    "chunks": [
        438
    ],
    "compressor": {
        "id": "zlib",
        "level": 3
    },
    "dtype": "<f8",
    "fill_value": "NaN",
    "filters": [
        {
            "elementsize": 8,
            "id": "shuffle"
        }
    ],
    "order": "C",
    "shape": [
        438
    ],
    "zarr_format": 2
}
```

Result in Kerchunk >=0.2.1:
```json
{
    "chunks": [
        438
    ],
    "compressor": null,
    "dtype": "<f8",
    "fill_value": "NaN",
    "filters": [
        {
            "elementsize": 8,
            "id": "shuffle"
        },
        {
            "id": "zlib",
            "level": 3
        }
    ],
    "order": "C",
    "shape": [
        438
    ],
    "zarr_format": 2
}
```

I'm a little unsure what the correct behaviour is here, since I'm not so familiar with the difference between compressors and filters in zarr. If the new behaviour is what it should be then we can update our code accordingly, but if the old behaviour is correct I'm happy to try to make a PR which appends zlib, blosc etc to compressors instead, but I would definitely need someone to verify that that is actually what should be happening and that I'm not breaking something else in doing so.

**Comment by martindurant** [comment]
In zarr2, compressor is simply the "last filter" and there is no technical difference between them, all are instances of numcodecs.abc.Codec . In zarr 3 (now in beta), this is even more explicit, and "compressor" isn't used at all. 

I htink the change in the code was made to simplify logic. You can try it, the two forms will be equivalent.

**Comment by alistaireverett** [comment]
In our code we were using `encoding["compressor"].get_config()` so things started failing when compressor was empty. I've updated our code now to avoid this though, so if this is expected behaviour we can just close the issue.

**Comment by martindurant** [comment]
OK, thanks for working around it. Looking forward to zarr 3, I think we might revisit this in the future, but for now using `filters` is convenient.
