### ISSUE TITLE
Proposal to add all-contributors bot to Kerchunk

### ISSUE THREAD

**Issue by Anu-Ra-g** [fsspec/kerchunk#503]
This is a proposal to add [all-contributors](https://allcontributors.org/docs/en/bot/installation) bot to `Kerchunk`.

**Comment by martindurant** [comment]
You think we don't credit code authors well for this repo?

**Comment by Anu-Ra-g** [comment]
It is just an thought I came up in regards to this [discussion](https://github.com/fsspec/kerchunk/pull/495#discussion_r1734964153).
